Clinical-Genomics/BALSAMIC

.travis.yml, README.rst, tests/install/test_install_conda.py
This PR adds .travis.yml, and build+coveralls status logo.
How to test:
1. Change branch on the browser travis_coverals_setup and the following should be visible:
2. Also, the target and image in the README.rst should be there.
1. README.rst should have two URLs+image and it should show the status. 
@ingkebil how does a PR should look like for documentation? Thanks in advance for looking into this.
=> Travis coverals setup

BALSAMIC/commands/config/__init__.py, BALSAMIC/commands/config/sample.py, tests/commands/config/test_config_sample.py, tests/commands/test_cli.py, tests/conftest.py
1. Functional testing added for config-sample command.
2. To get analysis type, `--umi` flag was added and `--analysis_type` was removed from config-sample command.
3. Based on this umi flag and normal sample, balsamic will calculate the analysis type.
**How to Test:**
1. Change the directory to BALSAMIC - `cd BALSAMIC`
2. Pull the code from `test_sample` branch
3. Run this `pytest tests/` - for functional testing
For `--umi` implementation:
1. Run `balsamic config sample --help`, to test implementation of `--umi` option
2. change the directory - `tests/test_data`
3. `--umi` option is a flag. Here, we are testing for `paired` analysis type. so, run balsamic with normal sample and without umi flag,
`balsamic config sample     --tumor fastq/S1_R_1.fastq.gz     --normal fastq/S2_R_1.fastq.gz …
=> Added new testcases for config-sample and UMI flag

BALSAMIC/utils/cli.py, tests/utils/test_utils.py
This PR adds test for cli_utils:createDir.
To test this PR:
`pytest -v tests/utils/test_utils.py::test_createDir`
Outcome:
All tests including test above should pass.
=> Test cli utils

tests/conftest.py, tests/utils/test_utils.py
This PR adds test for rule utils
1. get_conda_env
2. get_result_dir
How to test:
- `pytest -v tests/utils/test_utils.py::test_get_conda_env`
- `pytest -v tests/utils/test_utils.py::test_get_result_dir`
=> Test rule utils

BALSAMIC/commands/base.py, BALSAMIC/commands/config/reference.py, BALSAMIC/commands/config/sample.py, BALSAMIC/commands/run/analysis.py, BALSAMIC/commands/run/reference.py, requirements.txt, tests/commands/config/test_config_reference.py, tests/commands/config/test_config_sample.py
**This PR contains,**
- subprocess shell cmd execution removed from config-reference
- snakemake and graphviz module used to generate dag image file
- logging and coloredlogs added to BALSAMIC
**How to test**
- clone the repo, checkout to config branch
- Run pytest on tests dir
**Expected outcome**
- Testcases should run without error
- While running commands, logs should be shown
=> Config-reference command refactored and logging added

BALSAMIC/workflows/GenerateRef
This PR contains,
- md5 string generations added to GenerateRef workflow
- Genome version eg: `GRCh37` directory added to `basedir` 
- Fixed - variable name for known_indel_1kg
=> MD5 string generation in GenerateRef

BALSAMIC/snakemake_rules/variant_calling/mergetype.rule, BALSAMIC/snakemake_rules/variant_calling/mergetype_tumor.rule
This PR updates RG tags (PU, ID, SM, and PL) post merging to simplify unifying VCF merge in downstream analysis.
How to test:
- All unittests should pass.
- `normal.merged.bam` and `tumor.merged.bam` should have NORMAL and TUMOR as their RGSM
=> RG update post merging bam files of same type

BALSAMIC/commands/config/case.py
This PR adds support for multiple input fastq files for tumor samples for aggregation of QC
How to test:
- All unittests pass
- All QC workflows should run on every sample and aggregated results should be gathered via multiqc rule.
=> feat: multi tumor sample support

BALSAMIC/snakemake_rules/annotation/vep.rule, BALSAMIC/workflows/VariantCalling
- Updates VEP annotation format with custom cosmic tags
- The following tags should be added to CSQ field in INFO after annotation:
`COSMIC|COSMIC_CDS|COSMIC_GENE|COSMIC_STRAND|COSMIC_CNT|COSMIC_AA`
=> Vep cosmic

BALSAMIC/commands/config/case.py, BALSAMIC/commands/run/analysis.py, BALSAMIC/config/cluster.json, BALSAMIC/snakemake_rules/align/bwa_mem.rule, BALSAMIC/snakemake_rules/align/samtools.rule, BALSAMIC/snakemake_rules/annotation/vep.rule, BALSAMIC/snakemake_rules/quality_control/GATK.rule, BALSAMIC/snakemake_rules/quality_control/contest.rule, BALSAMIC/snakemake_rules/quality_control/fastp.rule, BALSAMIC/snakemake_rules/quality_control/fastqc.rule, BALSAMIC/snakemake_rules/quality_control/multiqc.rule, BALSAMIC/snakemake_rules/quality_control/picard.rule, BALSAMIC/snakemake_rules/quality_control/sambamba_depth.rule, BALSAMIC/snakemake_rules/sentieon/sentieon_alignment.rule, BALSAMIC/snakemake_rules/sentieon/sentieon_germline.rule, BALSAMIC/snakemake_rules/sentieon/sentieon_t_varcall.rule, BALSAMIC/snakemake_rules/sentieon/sentieon_tn_varcall.rule, BALSAMIC/snakemake_rules/variant_calling/cnvkit_paired.rule, BALSAMIC/snakemake_rules/variant_calling/cnvkit_single.rule, BALSAMIC/snakemake_rules/variant_calling/germline.rule, BALSAMIC/snakemake_rules/variant_calling/somatic_sv_tumor_normal.rule, BALSAMIC/workflows/Alignment, BALSAMIC/workflows/VariantCalling, BALSAMIC/workflows/VariantCalling_sentieon, requirements.txt
- TNscope and DNAscope added to sentieon rules
- TNscope filtering based on a machine learning model added
- DNAscope filtering disabled due to machine learning model issues
- Benchmark dir added to capture the processing time and CPU memory usage.
- Fixed fastp rule to write output json and html file for each sample.
=> Sentieon T/N and Tumor only pipeline updated 

BALSAMIC/snakemake_rules/variant_calling/cnvkit_single.rule, CHANGELOG.md
- Removes `--target` for cnvkit bach. It is redundant with `--reference`
=> fix: target bed is not required for wes runs

.travis.yml, BALSAMIC/workflows/VariantCalling_sentieon
- Fix: #246 Variant calling WGS will get sentieon models from assets dir instead of environment variables.
=> Get sentieon models from assets instead of env var

CHANGELOG.md, tests/commands/run/test_scheduler.py
- This PR fixes broken tests for new qsub case for #260 
Qsub:
- returns `Your job 501107 ("qsub_test.sh") has been submitted` as output.
- require -hold_jobid instead of afterok for building dependency trees.
- Addition of `-V` with following explanation from documentation (http://gridscheduler.sourceforge.net/htmlman/htmlman1/qsub.html):
```
-V   Available for qsub, qsh, qrsh with command and qalter.
Specifies that all environment variables active  within
the qsub utility be exported to the context of the job.
```
=> Qsub test update

BALSAMIC/snakemake_rules/quality_control/picard.rule, CHANGELOG.md
Added reference genome to be able to calculate AT/CG dropouts.
Run e.g. sample ACC5831A5 and compare the AT/CG dropout with the values provided by Twist.
A value from picard for the AT/CG dropout.
=> Added reference genome to be able to calculate AT/CG dropouts

BALSAMIC/assets/scout_config_template.yaml, BALSAMIC/commands/plugins/scout.py, CHANGELOG.md, tests/commands/plugins/test_scout.py
- scout plugin for balsamic is a bit more verbose. This was used to create config for following cases: https://github.com/Clinical-Genomics/Cancer-project/issues/37
=> refactor scout config generation

BALSAMIC/config/cluster_minimal.json, BALSAMIC/snakemake_rules/variant_calling/cnvkit_paired.rule, BALSAMIC/snakemake_rules/variant_calling/cnvkit_single.rule, BALSAMIC/workflows/GenerateRef, CHANGELOG.md, tests/test_data/references/reference.json
- VEP now also produces a tab delimited file
- CNVkit rules output genemetrics and gene break file
- Added reference genome to be able to calculate AT/CG dropouts by Picard
- coverage plot plugin part of issue #75
- callable regions for CNV calling of tumor-only
- Increased time for indel realigner and base recalib rules
- decoupled vep stat from vep main rule
- changed qsub command to match UGE
- scout plugin updated
- WGS qc rules - updated with correct options
(picard - CollectMultipleMetrics, sentieon - CoverageMetrics)
- Log warning if WES workflow cannot find SENTIEON* env variables
- Fixes issue with cnvkit and WGS samples #268
- Fix #267 coverage issue with long deletions in vardict
These workflows should finish without error:
=> Release 4.1.0

BALSAMIC/conda/BALSAMIC-py36.yaml, BALSAMIC/containers/Dockerfile.latest, BALSAMIC/snakemake_rules/annotation/vep.rule, BALSAMIC/snakemake_rules/sentieon/sentieon_t_varcall.rule, BALSAMIC/snakemake_rules/sentieon/sentieon_tn_varcall.rule, BALSAMIC/snakemake_rules/variant_calling/cnvkit_paired.rule, BALSAMIC/snakemake_rules/variant_calling/cnvkit_single.rule, BALSAMIC/snakemake_rules/variant_calling/germline.rule, BALSAMIC/snakemake_rules/variant_calling/somatic_sv_tumor_normal.rule, BALSAMIC/snakemake_rules/variant_calling/somatic_sv_tumor_only.rule, BALSAMIC/snakemake_rules/variant_calling/somatic_tumor_normal.rule, BALSAMIC/snakemake_rules/variant_calling/somatic_tumor_only.rule, BALSAMIC/workflows/VariantCalling, BALSAMIC/workflows/VariantCalling_sentieon, CHANGELOG.md
- refactor's vep rule
- adds namemaps to variant callers
- removes SV from vardict
- removes germline annotation
- removes tsv from vep's output
=> Vep refactor

BALSAMIC/snakemake_rules/variant_calling/split_bed.rule
- Fixes an issue with `sort` that looks for `$TMPDIR`
=> Set TMPDIR for splitbed rule

CHANGELOG.rst, install.sh
Refactors install script.
1. Adds support for conda env suffix
1. Updates script log output is more verbose, and outputs conda env name, container names, etc.
1. Cleans up path values and assigns them to a variable that can be reused.
- Install BALSAMIC via install script and check that it is working for:
1. release version
1. a specific branch
1. master
=> refactor, update container and add a cli option

.travis.yml, run_validate.sh
- Adds normal sample to run_validate script
- Removes run_validate from .travis.yaml
=> Add normal sample to run_validate

BALSAMIC/commands/config/case.py, BALSAMIC/utils/models.py
Refactor: Move all optional models into Balsamic config model.
Motivation:
Enabling flag "exclude_none"=True during model construction, solves the panel bed bug. 
This suggestion would solve the previous problem in desired way with minimum changes to the structure of the code.
=> Changes panel bed model

BALSAMIC/conda/varcall_cnvkit.yaml, BALSAMIC/conda/varcall_py27.yaml, BALSAMIC/conda/varcall_py36.yaml, BALSAMIC/config/balsamic_env.yaml, BALSAMIC/containers/Dockerfile.latest, BALSAMIC/snakemake_rules/variant_calling/cnvkit_paired.rule, BALSAMIC/snakemake_rules/variant_calling/cnvkit_single.rule, BALSAMIC/utils/cli.py, tests/utils/test_utils.py
Added: New conda env in container: varcall_cnvkit
Changed: Revert cnvkit back to 0.9.4
=> Fix/revert cnvkit 0.9.4

BALSAMIC/conda/varcall_py36.yaml, BALSAMIC/containers/Dockerfile.latest, BALSAMIC/containers/Dockerfile.release
Changed: Refactored Docker files a bit, preparation for decoupling
Fixed: Vardict-java version fixed. This is due to bad dependency and releases available on conda. Anaconda is not yet update with vardict 1.8, but vardict-java 1.8 is there. This causes various random breaks with Vardict's TSV output.
=> refactor docker files a bit, fix vardict-java version

BALSAMIC/snakemake_rules/sentieon/sentieon_alignment.rule, BALSAMIC/snakemake_rules/sentieon/sentieon_germline.rule, BALSAMIC/snakemake_rules/sentieon/sentieon_qc_metrics.rule, BALSAMIC/snakemake_rules/sentieon/sentieon_t_varcall.rule, BALSAMIC/snakemake_rules/sentieon/sentieon_tn_varcall.rule, BALSAMIC/snakemake_rules/umi/sentieon_consensuscall.rule, BALSAMIC/snakemake_rules/umi/sentieon_umiextract.rule, BALSAMIC/snakemake_rules/umi/sentieon_varcall_tnscope.rule, BALSAMIC/snakemake_rules/variant_calling/germline.rule, BALSAMIC/snakemake_rules/variant_calling/somatic_tumor_normal.rule, BALSAMIC/snakemake_rules/variant_calling/somatic_tumor_only.rule, BALSAMIC/utils/cli.py, BALSAMIC/workflows/UMIworkflow.smk, BALSAMIC/workflows/VariantCalling.smk, BALSAMIC/workflows/VariantCalling_sentieon.smk
Changed:
- Sentieon env vars moved to config
Added:
- Option `--clean-env` now added to each job
=> Add sentieon env vars to config file to get in rules instead

CHANGELOG.rst, README.rst, requirements.txt
=> Release 6.0.0

CHANGELOG.rst
[6.0.1]
------
- A secondary path for latest jobids submitted to cluster (slurm and qsub) PR #465
=> chanloge for 6.0.1

BALSAMIC/snakemake_rules/align/bwa_mem.rule, BALSAMIC/snakemake_rules/align/sentieon_alignment.rule, BALSAMIC/snakemake_rules/annotation/varcaller_filter.rule, BALSAMIC/snakemake_rules/annotation/vep.rule, BALSAMIC/snakemake_rules/quality_control/GATK.rule, BALSAMIC/snakemake_rules/quality_control/contest.rule, BALSAMIC/snakemake_rules/quality_control/fastp.rule, BALSAMIC/snakemake_rules/quality_control/fastqc.rule, BALSAMIC/snakemake_rules/quality_control/mosdepth.rule, BALSAMIC/snakemake_rules/quality_control/multiqc.rule, BALSAMIC/snakemake_rules/quality_control/picard.rule, BALSAMIC/snakemake_rules/quality_control/picard_wgs.rule, BALSAMIC/snakemake_rules/quality_control/sambamba_depth.rule, BALSAMIC/snakemake_rules/quality_control/sentieon_qc_metrics.rule, BALSAMIC/snakemake_rules/variant_calling/cnvkit_paired.rule, BALSAMIC/snakemake_rules/variant_calling/cnvkit_single.rule, BALSAMIC/snakemake_rules/variant_calling/germline.rule, BALSAMIC/snakemake_rules/variant_calling/mergetype.rule, BALSAMIC/snakemake_rules/variant_calling/mergetype_tumor.rule, BALSAMIC/snakemake_rules/variant_calling/sentieon_germline.rule, BALSAMIC/snakemake_rules/variant_calling/sentieon_t_varcall.rule, BALSAMIC/snakemake_rules/variant_calling/sentieon_tn_varcall.rule, BALSAMIC/snakemake_rules/variant_calling/somatic_sv_tumor_normal.rule, BALSAMIC/snakemake_rules/variant_calling/somatic_sv_tumor_only.rule, BALSAMIC/snakemake_rules/variant_calling/somatic_tumor_normal.rule, BALSAMIC/snakemake_rules/variant_calling/somatic_tumor_only.rule, BALSAMIC/snakemake_rules/variant_calling/split_bed.rule, BALSAMIC/workflows/balsamic.smk
Changed:
- move redundant variables into main workflow
=> crush redundant variables in rules and have one in the main workflow

BALSAMIC/containers/Dockerfile.develop, BALSAMIC/containers/Dockerfile.latest, BALSAMIC/containers/Dockerfile.release
Fixed:
- Removed `gatk3-register` from container as it is not used anymore to activate gatk3 when creating environment inside container
=> remove gatk3-register command

BALSAMIC/containers/Dockerfile.latest, BALSAMIC/containers/Dockerfile.release
Fixed:
- Removed the deprecated `gatk3-register` command
=> remove gatk3-register

.github/workflows/docker_build_test.yml, .github/workflows/pytest_and_coveralls.yml, BALSAMIC/utils/constants.py, BALSAMIC/utils/models.py, BALSAMIC/workflows/balsamic.smk, requirements-dev.txt
Removed:
- Strelka2 and Mutect2(gatk3.8) from germline and somatic variant calling respectively.
=> Remove Strelka and Mutect2 from somatic variant calling

BALSAMIC/snakemake_rules/annotation/vep.rule, BALSAMIC/snakemake_rules/quality_control/GATK.rule, BALSAMIC/snakemake_rules/variant_calling/split_bed.rule
Fixed:
- Linux `readlink` command in `vep_germline`, `vep_somatic`, `split_bed`, and `GATK_popVCF`
=> readlink command fix according to container

BALSAMIC/utils/constants.py
Fixed:
- Reduces MQ cutoff from 50 to 40 to only remove obvious artifacts.
- Reduces AF cutoff from 0.02 to 0.01
=> Hotfix, reduce MQ filter cutoff to 40

BALSAMIC/containers/varcall_py36/varcall_py36.yaml, tests/utils/test_utils.py
Changed:
- bumped bcftools version from 1.10.2 to 1.11
=> bump up bcftools

BALSAMIC/commands/report/deliver.py
Fixed:
- Options for generating QC report via `balsamic report deliver` are not mandatory anymore.
=> make qc report optional

BALSAMIC/commands/report/deliver.py, CHANGELOG.rst
Changed: hk delivery tag for coverage-qc-report
See e.g. https://github.com/Clinical-Genomics/hermes/pull/13 and https://github.com/Clinical-Genomics/cg/issues/987
=> Change hk deliverable tag for coverage qc report

BALSAMIC/snakemake_rules/variant_calling/sentieon_germline.rule, BALSAMIC/snakemake_rules/variant_calling/sentieon_t_varcall.rule, BALSAMIC/snakemake_rules/variant_calling/sentieon_tn_varcall.rule
For Sentieon wgs rules (TNscope, TNhaplotyper and DNAscope), setting the pcr-free-indel model to NONE.
=> setting sentieon wgs to pcr-free

BALSAMIC/snakemake_rules/umi/sentieon_varcall_tnscope.rule, BALSAMIC/snakemake_rules/umi/sentieon_varcall_tnscope_tn.rule, BALSAMIC/utils/constants.py, BALSAMIC/utils/models.py, CHANGELOG.rst, tests/utils/test_models.py
Variant calling with TNScope in UMIworkflow, tumor lod option uses the default (value 6.2) for passing the final called variants. Now added this parameter to the command-line, and the default value can be controlled via constants.
Tumor LOD default values for tumor and normal in SENTIEON are set according to the mutect. Read more [here](https://software.broadinstitute.org/cancer/cga/mutect)
=> add tumor lod option for passing final variants

BALSAMIC/snakemake_rules/annotation/varcaller_filter_tumor_normal.rule, BALSAMIC/snakemake_rules/annotation/varcaller_filter_tumor_only.rule, BALSAMIC/snakemake_rules/annotation/varcaller_wgs_filter_tumor_normal.rule, CHANGELOG.rst
Fixed:
- vcf-filtered-clinical tag only had PASSed variants with further filters. Fixed such it also preserves VarDict filters and not just `PASS`
=> Include all filtered variants in vcf-filtered-clinical not just PASSed

BALSAMIC/containers/annotate/annotate.yaml, BALSAMIC/utils/cli.py, CHANGELOG.rst
Added:
- `vcf2cytosure` as dependency in annotate container first part of #605
=> Add vcf2cytosure as dependency

BALSAMIC/snakemake_rules/annotation/varcaller_wgs_filter_tumor_only.rule, BALSAMIC/snakemake_rules/dragen_suite/dragen_dna.rule, BALSAMIC/snakemake_rules/quality_control/GATK.rule, BALSAMIC/snakemake_rules/quality_control/contest.rule, BALSAMIC/snakemake_rules/quality_control/fastp.rule, BALSAMIC/snakemake_rules/quality_control/fastqc.rule, BALSAMIC/snakemake_rules/quality_control/mosdepth.rule, BALSAMIC/snakemake_rules/quality_control/multiqc.rule, BALSAMIC/snakemake_rules/quality_control/picard.rule, BALSAMIC/snakemake_rules/quality_control/picard_wgs.rule, BALSAMIC/snakemake_rules/quality_control/sambamba_depth.rule, BALSAMIC/snakemake_rules/quality_control/sentieon_qc_metrics.rule, BALSAMIC/snakemake_rules/variant_calling/split_bed.rule, CHANGELOG.rst
Refactor quality control snakemake rules  according to snakemake etiquette
Part of #636
=> refactor quality control rules

BALSAMIC/snakemake_rules/annotation/vep.rule, CHANGELOG.rst
Fixes:
- Use bcftools stats to generate Ti/TV which will be picked up by MultiQC #93
=> fix: uses bcftools stats to generate ti/tv

BALSAMIC/containers/align_qc/align_qc.sh, BALSAMIC/containers/varcall_py36/varcall_py36.sh, BALSAMIC/containers/varcall_py36/varcall_py36.yaml, CHANGELOG.rst
Fixed:
- Removed libreadline linking, and fixed R version to 3.6.2 fixes #739
=> fix: removed libreadline.so symlinking, and fixed R version to 3.6.2 for varcall_py36 container

BALSAMIC/workflows/PON.smk, CHANGELOG.rst
Changed:
Rename the PON reference filename with more descriptive details as from which panel and case_id, the output PON is generated. Related to https://github.com/Clinical-Genomics/cgp-cancer-cnvcall/issues/10
To reproduce:
```
balsamic config pon --case-id securetoad10 -p /home/proj/production/cancer/reference/target_capture_bed/production/balsamic/gmcksolid_4.1_hg19_design.bed --balsamic-cache /home/proj/stage/cancer/balsamic_cache/ --analysis-dir /home/proj/long-term-stage/cancer/PON_analysis_runs_APJ/PON_test_datasets/ --fastq-path /home/proj/production/cancer/cases/securetoad/fastq/ -g hg19
balsamic run analysis -s /home/proj/long-term-stage/cancer/PON_analysis_runs_APJ/PON_test_datasets/securetoad10/securetoad10_PON.json 
```
=> refactor: rename pon reference filename

BALSAMIC/containers/align_qc/align_qc.yaml, CHANGELOG.rst
Fixed:
- fixes #744 by bumping multiqc to most recent version
=> fix: bcftools stats not parsed by MultiQC

BALSAMIC/snakemake_rules/quality_control/multiqc.rule, CHANGELOG.rst
Fixed:
- fixes #746 by excluding VEP from multiqc due to a bug with multiqc
=> fix: remove VEP from multiqc modules

BALSAMIC/containers/varcall_cnvkit/varcall_cnvkit.yaml, CHANGELOG.rst, setup.py
Lock `cryptography` package version.
=> fix: cryptography version to address failing builds

CHANGELOG.rst, README.rst
Fixed: Currently the docker badge for "Container master status" is shown as "Not found".
This PR fixes the correct URL path for displaying the badge "passing"
=> fix: container master status docker badge 

.bumpversion.cfg, BALSAMIC/containers/align_qc/Dockerfile, BALSAMIC/containers/annotate/Dockerfile, BALSAMIC/containers/coverage_qc/Dockerfile, BALSAMIC/containers/varcall_cnvkit/Dockerfile, BALSAMIC/containers/varcall_py27/Dockerfile, BALSAMIC/containers/varcall_py36/Dockerfile, CHANGELOG.rst
Fixed:
- bumpversion for main Dockerfile in `.bumpversion.cfg`
=> fix: bumpversion for main Dockerfile

BALSAMIC/snakemake_rules/variant_calling/cnvkit_paired.rule, BALSAMIC/snakemake_rules/variant_calling/cnvkit_single.rule, CHANGELOG.rst
Fixes the `cnvkit.py` call error made from `cnvkit_single.rule` and `cnvkit_paired.rule` during the validation of `BALSAMIC 8.2.0` on stage using the PANEL_UMI TUMOR_ONLY CASE (`uphippo`).
`uphippo` validation case log:
=> fix: cnvkit gender comparison operator

BALSAMIC/containers/varcall_cnvkit/varcall_cnvkit.yaml, BALSAMIC/snakemake_rules/variant_calling/cnvkit_paired.rule, BALSAMIC/snakemake_rules/variant_calling/cnvkit_single.rule, CHANGELOG.rst
Fixes #824 
- Possibility to report dual information about gender info in purecn/TUMOR.CSV file. Could be because of noisy data, contamination, loss of chrY, or misalignment of coverage and VCF.
- In such cases, consider gender as default `m`
- Updated `purecn` and its dependencies to latest versions.
=> fix: cnvkit genderissue

BALSAMIC/constants/workflow_params.py, BALSAMIC/snakemake_rules/umi/sentieon_varcall_tnscope.rule, BALSAMIC/snakemake_rules/umi/sentieon_varcall_tnscope_tn.rule, BALSAMIC/utils/models.py, CHANGELOG.rst, tests/utils/test_models.py
While calling UMI variants using TNscope, use the panel-defined regions to restrict calls.
Fixes : #821
=> refactor: umi intervalbed

BALSAMIC/assets/scripts/collect_qc_metrics.py, BALSAMIC/constants/quality_check_reporting.py, CHANGELOG.rst, tests/conftest.py, tests/scripts/test_collect_qc_metrics.py
Fixes #854.
- Condition (`METRIC` constant):
- Extracted metrics (`<case_id>_metrics_deliverables.yaml`):
- Validation successfully fails for the `panel.bed` test file (BALSAMIC.TN_panel.all.0.sh_<job_id>.err):
=> fix: QC panel bed version generalisation

BALSAMIC/constants/variant_filters.py, CHANGELOG.rst, README.rst, docs/balsamic_filters.rst, docs/user_guide.rst
Changed: 
Filter for reporting somatic variants (Vardict) VAF is minimised to 0.7% from 1%. Related to https://github.com/Clinical-Genomics/project-planning/issues/377#issuecomment-1060291718
Updated the balsamic documents for variant calling filters and balsamic repo contributors
=> fix: balsamic low vaf

.github/workflows/sphinx_docs.yml, CHANGELOG.rst, docs/conf.py, setup.py
Adresses `ModuleNotFoundError: No module named 'numpy'` when building the docs:
https://readthedocs.org/projects/balsamic/builds/16287901/
Solution from:
https://read-the-docs.readthedocs.io/en/latest/faq.html#i-get-import-errors-on-libraries-that-depend-on-c-modules
https://www.sphinx-doc.org/en/master/usage/extensions/autodoc.html#confval-autodoc_mock_imports
=> fix: docs importing C dependant libraries

.readthedocs.yml, CHANGELOG.rst, docs/conf.py, setup.py
Mocks cyvcf2 import  to build documentation.
Tested successfully in a fork repository ([ivadym/BALSAMIC](https://github.com/ivadym/BALSAMIC)):
https://readthedocs.org/projects/balsamic-docs/builds/16310624/
=> fix: dock build mocking cyvcf dependency

BALSAMIC/constants/workflow_params.py, BALSAMIC/snakemake_rules/annotation/varcaller_sv_filter.rule, CHANGELOG.rst
Added: SVdb merge manta and delly for TGA workflow.
=> feat: add svdb workflow tga

BALSAMIC/constants/workflow_params.py, BALSAMIC/containers/varcall_py36/varcall_py36.yaml, BALSAMIC/snakemake_rules/variant_calling/somatic_sv_tumor_normal.rule, BALSAMIC/snakemake_rules/variant_calling/somatic_sv_tumor_only.rule, BALSAMIC/utils/models.py, BALSAMIC/utils/rule.py, BALSAMIC/workflows/balsamic.smk, CHANGELOG.rst
=> feat: svdb merge sv cnv

BALSAMIC/snakemake_rules/quality_control/fastp.rule, BALSAMIC/utils/models.py, CHANGELOG.rst, tests/utils/test_models.py
Fixes: #904 
Added: 
- Extended the QCModel to include `n_base_limit` which outputs in config json `QC` dict
=> fix: change default fastp n_base_limit settings 

BALSAMIC/assets/scripts/collect_qc_metrics.py, BALSAMIC/constants/quality_check_reporting.py, BALSAMIC/utils/models.py, CHANGELOG.rst, tests/scripts/test_collect_qc_metrics.py, tests/test_data/qc_files/analysis/qc/multiqc_data/multiqc_data.json
Added new WGS metrics to be extracted and stored to `<case>_metrics_deliverables.yaml`.
=> feat: extract additional WGS metrics

.bumpversion.cfg, CHANGELOG.rst, docs/balsamic_methods.rst
- Adds bump version to update for version number in[ balsamic_method documentation.](https://balsamic.readthedocs.io/en/latest/balsamic_methods.html) 
- Currently changed manually, automatic version updated from next release.
=> docs: update balsamic method version in bumpversion

BALSAMIC/snakemake_rules/variant_calling/somatic_sv_tumor_normal.rule, CHANGELOG.rst
Fixed:
- Missing `genderChr` flag for `ascat_tumor_normal` rule
=> fix: missing genderChr flag for ascat

BALSAMIC/workflows/QC.smk, CHANGELOG.rst
`analysis_dir` is not defined in the QC.smk. Failed to create `balsamic config case ` with `-w balsamic-qc` option.
More details in the screenshot
=> fix:  missing name `analysis_dir` in qc workflow

BALSAMIC/config/cluster.json, BALSAMIC/snakemake_rules/variant_calling/somatic_sv_tumor_normal.rule, BALSAMIC/snakemake_rules/variant_calling/somatic_sv_tumor_only.rule, CHANGELOG.rst
When fixing the TIDDIT shell calls, the rule names were also changed https://github.com/Clinical-Genomics/BALSAMIC/pull/973. However, the delivery rules were not updated accordingly.
This PR undoes those name changes in order to re-include the TIDDIT files in the delivered `.hk` file.
=> fix: tiddit delivery rule names

BALSAMIC/containers/varcall_py3/varcall_py3.yaml, CHANGELOG.rst, container_tests/varcall_py3/varcall_py3.sh
Added: `cnvpytor` to varcall_py3 container.
=> feat: added cnvyptor to varcall_py3 container

BALSAMIC/containers/varcall_cnvkit/varcall_cnvkit.yaml, CHANGELOG.rst
Added: R packages to cnvkit container.
=> fix: cnvkit container

BALSAMIC/config/cluster.json, BALSAMIC/snakemake_rules/quality_control/sambamba_depth.rule, CHANGELOG.rst
Recent cases failed on run time for the sambamba_exon_depth rule:
`slurmstepd: error: *** JOB 3715107 ON compute-0-11 CANCELLED AT 2022-09-22T22:01:04 DUE TO TIME LIMIT ***`
=> fix: Increase sambamba run time

BALSAMIC/constants/workflow_params.py, BALSAMIC/snakemake_rules/variant_calling/mergetype_normal.rule, BALSAMIC/snakemake_rules/variant_calling/mergetype_tumor.rule, BALSAMIC/utils/models.py, CHANGELOG.rst
The bam files generated multiple errors showing an invalid bam flag for numerous reads. Samtools could fix a few of them, but not all. Picard tools fixmateinformation command performs better than samtools and fixes the invalid bam flags.
The origin of these errors is concatenated fastq file. The current PR fixes the issue, but it would be better to use each fastq as input and merge bam files instead.
Fixed: invalid bam flag using `Picard tools`.
=> fix: invalid bam flag using picardtools

BALSAMIC/constants/workflow_rules.py, BALSAMIC/snakemake_rules/variant_calling/sentieon_split_snv_sv.rule, BALSAMIC/snakemake_rules/variant_calling/sentieon_t_varcall.rule, BALSAMIC/snakemake_rules/variant_calling/sentieon_tn_varcall.rule, CHANGELOG.rst
Fixed:  Incorrect raw TNscope VCF delivered. We were delivering the ALL.tnscope file, including SNVs and SVs
=> fix: Incorrect raw TNscope delivered VCF

BALSAMIC/snakemake_rules/variant_calling/somatic_sv_quality_filter.rule, CHANGELOG.rst
Fixed: `bfcftools` filter command in SV quality filter to not filter out variants that are filtered out as `MaxDepth`.
=> fix: SV quality filter

BALSAMIC/workflows/reference.smk, CHANGELOG.rst
Fixes https://github.com/Clinical-Genomics/BALSAMIC/issues/1064 
Changed: parallelize download of reference files
=> perf: Parallelize download reference

BALSAMIC/workflows/reference.smk, CHANGELOG.rst
Fixes https://github.com/Clinical-Genomics/BALSAMIC/issues/1066 
Changed: parallelize download of container images
=> perf: Parallelize container download

BALSAMIC/containers/somalier/Dockerfile, CHANGELOG.rst
Addresses security hotspot related to using alpine docker with the default root user in somalier. It changes it to `defaultuser` instead
Fixed: somalier container user to non-root user
=> fix: change somalier container user to defaultuser

CHANGELOG.rst, setup.py
Addresses security alerts linked to cryptography version:
https://github.com/Clinical-Genomics/BALSAMIC/security/dependabot/2
It will also fix the critical alert dismissed in the past:
https://github.com/Clinical-Genomics/BALSAMIC/security/dependabot/1
=> refactor: Update cryptography version

BALSAMIC/config/cluster.json, CHANGELOG.rst
Increases time-limit for commonly timeout processes, picard_markduplicates and sambamba_exon_depth
Changed: 
* Increase time-limit for picard_markduplicates and sambamba_exon_depth to 6 hours
=> fix: increase_time_for_processes

BALSAMIC/constants/workflow_params.py, BALSAMIC/containers/annotate/annotate.yaml, CHANGELOG.rst
Aims to solve the issue mentioned here: https://github.com/Clinical-Genomics/BALSAMIC/issues/1123 where SV calls longer than the default max_sv_size are filtered out rather than simple being left un-annotated in the output VCF (in versions  > 109 of VEP this was changed so that variants are not filtered out).
Another way to keep all variants, as well as to annotate them, is simply to increase the max_sv_size to the maximum possible size (the size of chromosome 1: 249250621 for hg19, which is larger than chromosome 1 in hg38 and should therefore be fine for both genome versions).
**Changed: for changes in existing functionality.**
=> fix: VEP filters away variants too long to annotate

CHANGELOG.rst, setup.py
Balsamic init was not able to download reference files from GS.
Cryptography version update was not compatible with pyOpenssL:
* Bump cryptography to v40.0.2 and gsutil to v5.23
=> fix: Update tools versions for balsamic init

CHANGELOG.rst, docs/balsamic_annotation.rst, docs/balsamic_filters.rst, docs/balsamic_sv_cnv.rst
Updates read the docs for release 12.0.0 of balsamic.
**Added:**
- PIP specific missing tools to config https://github.com/Clinical-Genomics/BALSAMIC/pull/1096
- Filtering script to remove normal variants from TIDDIT feat: add TIDDIT tumor normal filtering  #1120
- Store TMB files in HK https://github.com/Clinical-Genomics/BALSAMIC/pull/1144
**Changed:**
- Fixed all conda container dependencies https://github.com/Clinical-Genomics/BALSAMIC/pull/1096
- Changed --max_sv_size in VEP params to the size of chr1 for hg19 https://github.com/Clinical-Genomics/BALSAMIC/pull/1124
- Increased time-limit for sambamba_exon_depth and picard_markduplicates to 6 hours https://github.com/Clinical-Genomics/BALSAMIC/pull/1143
- Update cosmicdb to v97 perf: COSMIC database to v97  #1147
**Fixed:**
- Update …
=> fix: update read the docs for balsamic v12.0.0

CHANGELOG.rst, setup.py
Pydantic v2, which introduced breaking changes, has been released: https://github.com/pydantic/pydantic/releases/tag/v2.0,  causing pytest and model misbehaviour.
- Fix Pydantic version (<2.0)
=> fix: pydantic version to <2.0

BALSAMIC/commands/config/case.py, BALSAMIC/commands/config/pon.py, BALSAMIC/commands/run/analysis.py, BALSAMIC/utils/cli.py, CHANGELOG.rst, tests/utils/test_utils.py
During testing, it was discovered that the `balsamic config case` command failed when the provided FASTQ directory was outside the case folder. This issue was not encountered when the command was run through CG, as CG creates and links the necessary files in the case directory. 
To ensure that the command works as expected in all scenarios, the code has been modified to create the case directory if it does not exist and link the fastq files from the provided fastq directory.
=> fix: Link external fastqs to case folder & create case directory

.github/workflows/docker_build_push.yml, BALSAMIC/containers/vcf2cytosure/Dockerfile, CHANGELOG.rst
Fixed: vcf2cytosure missing constants by fixing python version to 3.11.3. Python 3.11.4 caused the error.
=> fix: vcf2cytosure container missing constants

.github/workflows/docker_build_push.yml, CHANGELOG.rst, setup.py
The recent Cython update to v0.30 has led to compilation errors, resulting in the failure to execute the Balsamic container and, more importantly, preventing pytest from running via GitHub actions.
- Fix cyvcf2 to version 0.30.22
=> fix: Balsamic container & pytests (fix cyvcf2 version)

.github/workflows/docker_build_publish_develop.yml, .github/workflows/docker_build_publish_release.yml, BALSAMIC/constants/cache.py, BALSAMIC/containers/htslib/Dockerfile, BALSAMIC/containers/htslib/htslib.yaml, CHANGELOG.rst, container_tests/htslib/htslib.sh, docs/README.rst, docs/balsamic_annotation.rst, docs/index.rst, docs/programming_guide.rst, tests/conftest.py
Added: htslib container with samtools, bcftools, tabix and bgzip.
=> feat: add htslib container

BALSAMIC/containers/cnvpytor/Dockerfile, CHANGELOG.rst
=> fix: CNVpytor container (fix numpy version to 1.23.5)

BALSAMIC/models/snakemake.py, CHANGELOG.rst, tests/models/test_snakemake_models.py
- Migrate Snakemake models to pydantic v2
=> chore: Migrate Snakemake models to pydantic v2

BALSAMIC/commands/init/base.py, BALSAMIC/models/cache.py, BALSAMIC/workflows/reference.smk, CHANGELOG.rst, tests/conftest.py, tests/models/test_cache_models.py
- Migrate cache models to pydantic v2
=> chore: Migrate cache models to pydantic v2

BALSAMIC/commands/options.py, BALSAMIC/constants/analysis.py, BALSAMIC/constants/cache.py, BALSAMIC/constants/cluster.py, BALSAMIC/constants/constants.py, BALSAMIC/models/snakemake.py, BALSAMIC/utils/class_types.py, CHANGELOG.rst, tests/conftest.py, tests/models/test_snakemake_models.py
After upgrading to Python 3.11, we can now use `StrEnum` directly from the `enum` module. There's no longer a need to access` .value`, as we can work with these constants directly.
=> refactor: Use StrEnum from python enum 

BALSAMIC/snakemake_rules/variant_calling/gens_preprocessing.rule, CHANGELOG.rst
With the current implementation, `balsamic report deliver` will generate redundant tags for HK: `gens-gens-input-bgz`. Changing it to `cnv-gens-bed`.
=> refactor: Update gens tags

BALSAMIC/snakemake_rules/variant_calling/gens_preprocessing.rule, CHANGELOG.rst
Fixes:
```
/bin/bash: line 1: /home/proj/stage/bin/miniconda3/envs/S_balsamic/lib/python3.11/site-packages/BALSAMIC/assets/scripts/preprocess_gens.py: Permission denied
```
=> fix: gens_preprocessing rule missing python directive

BALSAMIC/constants/constants.py, BALSAMIC/constants/paths.py, BALSAMIC/utils/analysis.py, CHANGELOG.rst, tests/utils/test_utils.py
String has been assigned instead of a Path for CADD annotations. There are also some code smells that we overlooked.
=> fix: CADD annotations container path & (some) code smells

.github/ISSUE_TEMPLATE/user_story.yml
Fixes error introduced with last PR
Fixed: Now all labels are unique
=> chore: fix non-unique labels in user story template

CHANGELOG.rst
We have to include an `__init__.py` file in the newly created folders for the `find_packages()` function to be able to find the files present in them. `site_packages` is currently empty:
```
Failed to open source file /home/proj/stage/bin/miniconda3/envs/S_balsamic/lib/python3.11/site-packages/BALSAMIC/snakemake_rules/misc/sleep.rule
FileNotFoundError: [Errno 2] No such file or directory: '/home/proj/stage/bin/miniconda3/envs/S_balsamic/lib/python3.11/site-packages/BALSAMIC/snakemake_rules/misc/sleep.rule'
```
=> fix: Missing init in snakemake_rules folder

BALSAMIC/commands/options.py, BALSAMIC/commands/report/deliver.py, BALSAMIC/constants/analysis.py, BALSAMIC/constants/constants.py, BALSAMIC/utils/cli.py, BALSAMIC/utils/delivery.py, BALSAMIC/utils/io.py, CHANGELOG.rst, tests/commands/report/test_deliver.py, tests/conftest.py, tests/utils/test_delivery.py, tests/utils/test_utils.py
Add MultiQC intermediates files to the deliverables `.hk` file.
- MultiQC intermediate files to deliverables
- `delivery.py`, removing unused arguments 
<details>
- Tested in https://github.com/Clinical-Genomics/hermes/pull/95
</details>
- **PR …
=> feat: Deliver MultiQC intermediate files

BALSAMIC/snakemake_rules/variant_calling/somatic_sv_tumor_normal.rule, CHANGELOG.rst
Correct bcftools filter in tumor / normal Manta rule to use the tumor column instead of the normal (bug). 
Issue was discovered during validation that the bcftools filter in the manta_tumor_normal rule was using the normal column for filtering (index 0) instead of the tumor (index 1). This is not an issue in the manta_tumor_only as the tumor there is index 0. By switching the sample in the tumor_normal manta rule to index 1 for the filter, it should work as expected.
Fixed: for any bug fixes.
- switched to use column 2 in the bcftools filter for the low_prsr filter in manta_tumor_normal rule
Run bcftools on the raw somantic manta calls on tumor-normal cases and confirm that it applies filter on tumor column in sample: K (see https://docs.google.com/document/d/12x3ozQE62bk_yWNTBW_u8vZMqhpKF …
=> fix: use correct bcftools filter column for tumor in manta tumor only

BALSAMIC/snakemake_rules/variant_calling/somatic_cnv_tumor_normal_tga.rule, BALSAMIC/snakemake_rules/variant_calling/somatic_cnv_tumor_only_tga.rule, CHANGELOG.rst
PureCN rule fails due to bash strict mode when purity and ploidy can not be estimated. This causes the whole pipeline to terminate prematurely.
- PureCN rules to bypass bash strict mode in both TO and TN workflows.
- [Screenshot]
<details>
</details>
> Ensure that all checkboxes below are ticked before …
=> fix: PureCN rules

BALSAMIC/snakemake_rules/pon/cnvkit_create_pon.rule, CHANGELOG.rst
When cnvkit container was renamed it was forgotten to be updated in the PON workflow rules that uses cnvkit. This PR aims to correct this bug. 
- [Description]
- Name of the containers in the rules changed to cnvkit.sif
- [Description]
- [Description]
- [Screenshot]
<details>
</details>
> Ensure that all …
=> fix: bug in pon workflow

.github/workflows/docker_build_publish_develop.yml, .github/workflows/docker_build_publish_release.yml, BALSAMIC/constants/analysis.py, BALSAMIC/constants/cache.py, BALSAMIC/containers/msisensorpro/Dockerfile, BALSAMIC/containers/msisensorpro/msisensorpro.yaml, CHANGELOG.rst, container_tests/msisensorpro/msisensorpro.sh, docs/bioinfo_softwares.rst, tests/conftest.py, tests/test_data/config.json
Add MSIsensor-pro container
- Add MSIsensor-pro container
- [Screenshot]
<details>
</details>
- **Tests**
- **Review**
- **Code**
- **Tests**
conditions where applicable, with …
=> feat: add msisensorpro container

.gitignore, BALSAMIC/commands/config/case.py, BALSAMIC/commands/options.py, BALSAMIC/models/config.py, BALSAMIC/utils/cli.py, BALSAMIC/workflows/balsamic.smk, CHANGELOG.rst, tests/utils/test_utils.py
Patch release `v15.0.1`
> [15.0.1]
> -------
> 
> Added:
> ^^^^^^
> * CLI option for the minimum raw reads supporting each UMI group filter
https://github.com/Clinical-Genomics/BALSAMIC/issues/1451
- **Tests**
- **Review**
- **Code**
- **Tests**
conditions where applicable, with satisfactory results.
- **Review**
=> feat: Release v15.0.1

BALSAMIC/snakemake_rules/annotation/msi_tumor_normal.rule, BALSAMIC/snakemake_rules/report/generate_pdf.rule, CHANGELOG.rst, docs/balsamic_annotation.rst
Update MSI final table.
- [Description]
- MSI final table
- [Description]
- [Description]
- [Screenshot]
<details>
</details>
- **Tests**
- **Review**
- **Code**
- **Tests**
conditions …
=> fix: update MSI table

BALSAMIC/constants/cluster_analysis.json, CHANGELOG.rst
During validation, a we noticed that cores allocation for vardict_tumor_only is variable from 5 to 10 for different chromosomes.
- Increase allocation of cores for vardict_tumor_only to 18
- [Description]
- [Screenshot]
<details>
</details>
- …
=> fix: Increase vardict tumor only cores allocation to 18

BALSAMIC/constants/cluster_analysis.json, BALSAMIC/snakemake_rules/variant_calling/snv_t_varcall_tga.rule, BALSAMIC/snakemake_rules/variant_calling/snv_tn_varcall_tga.rule, BALSAMIC/snakemake_rules/variant_calling/vardict_pre_and_postprocessing.rule, CHANGELOG.rst
VarDict is failing on a frequency of about 1/120 jobs. Each case we're submitting has 24 jobs for VarDict as we're splitting them up per chromosome. As we have not been able to solve the VarDict issue I would argue that a reasonable way of reducing the effect of it could be to remove the amount of VarDict jobs per case, by removing the parallelisation per chromosome. 
On an average panel case each VarDict chromosome job has finished in under a minute, even when running only on 1 thread. 
- remove parallelization per chromosome for VarDict
See table below for the same case, running VarDict in parallel per chromosome vs running the entire bamfile at once **(last row)**.
The total amount of seconds run on the cluster for the parallel jobs were: 1231 where as it took 350 …
=> fix: remove vardict parallelization per chrom
