Clinical-Genomics/BALSAMIC

BALSAMIC/containers/BALSAMIC.def, README.rst
This PR adds singularity container for core BALSAMIC.
=> feat: added singularity container def file and badge

BALSAMIC/commands/install/install.py, install.sh
This PR addresses issues with https://github.com/Clinical-Genomics/cg/issues/364 
To test this PR:
1. `git checkout install_singularity`
2. `./install.sh -s S -d 190528_HFA -p ${CONDA_ENVS_PATH} -c`
=> Install balsamic through conda container

BALSAMIC/commands/run/run_analysis.py
This PR adds support for multiple snakemake_opt option in balsamic run command.
=> Multiple option for snakemake_opt

BALSAMIC/commands/config/report.py, BALSAMIC/commands/report/report.py, BALSAMIC/tools/__init__.py, BALSAMIC/tools/cli_utils.py, tests/commands/config/test_config_sample.py, tests/commands/test_cli.py, tests/conftest.py, tests/tools/test_utils.py
Test cases added for run cli-command, cli-utils and rule utils.
**How to test**
1.  Pull the latest code and change the directory to BALSAMIC - `cd BALSAMIC`
2.  Checkout the test_run_cli branch
3. Run  `pytest tests/`
**Expected outcome**
1. Pytest should be run without any error.
2. It should have 38 passed test cases
=> Unit Test added for run cli and utils 

BALSAMIC/commands/config/sample.py, tests/commands/config/test_config_sample.py, tests/conftest.py
**This PR contains,**
- refactoring of link_fastq with try and exception
- Added test cases for new functions 
**How to Test:**
- clone this repo, then cd BALSAMIC
- Run pytest, `pytest tests/`
**Expected outcome:**
-  Test cases should be passed without error
=> Added validation for link fastq and test cases

.pytest.ini, .travis.yml, BALSAMIC/commands/config/reference.py, BALSAMIC/commands/config/sample.py, tests/commands/config/test_config_sample.py, tests/commands/run/test_run_analysis.py, tests/commands/test_cli.py, tests/conftest.py
This PR adds bunch of new fixtures, and tests run analysis
=> Tests and fixtures for testing run analysis

BALSAMIC/snakemake_rules/align/bwa_mem.rule, BALSAMIC/snakemake_rules/quality_control/collectqc_paired.rule, BALSAMIC/snakemake_rules/quality_control/collectqc_single.rule, BALSAMIC/snakemake_rules/quality_control/fastqc.rule, BALSAMIC/workflows/Alignment, BALSAMIC/workflows/VariantCalling_paired, BALSAMIC/workflows/VariantCalling_single
This PR temporarily removes cutadapt from all three workflows.
=> refactor: removes cutadapt from workflow

BALSAMIC/commands/run/analysis.py, BALSAMIC/commands/run/sbatch.py, BALSAMIC/utils/cli.py, tests/commands/run/test_sbatch.py, tests/utils/test_utils.py
This PR:
- refactors `sbatch.py`
- renames `sbatch` class to `SbatchScheduler` and it is moved into `sbatch.py`
How to test:
- All tests on travis should pass
- Submit a qc run to slurm.
- All jobs should be submitted to slurm without any issue and finish successfully.
=> Refactor sbatch

BALSAMIC/commands/plugins/housekeeper.py, BALSAMIC/snakemake_rules/quality_control/multiqc.rule, BALSAMIC/workflows/Alignment, BALSAMIC/workflows/VariantCalling_paired, BALSAMIC/workflows/VariantCalling_single
This PR adds multiqc and housekeeper yaml generation.
- generating multiqc report and housekeeper file after analysis if is finished
How to test:
- All unittests should pass
=> Multiqc addition

BALSAMIC/snakemake_rules/quality_control/multiqc.rule
- Temporary fix on analysis/qc directory with permission issues
=> fix: change permission for qc dir

BALSAMIC/commands/config/case.py, BALSAMIC/config/analysis.json, BALSAMIC/utils/rule.py
- QC params for fastp fixed by changing string to boolean values in the analysis config file.
=> analysis.json string replaced by boolean values 

BALSAMIC/snakemake_rules/sentieon/sentieon_germline.rule, BALSAMIC/snakemake_rules/sentieon/sentieon_tn_varcall.rule
- Fixed sentieon_dnascope cmd 
- Removed unicode character from the co-realign cmd 
=> sentieon commands fixed

BALSAMIC/snakemake_rules/variant_calling/cnvkit_paired.rule, BALSAMIC/snakemake_rules/variant_calling/cnvkit_single.rule, BALSAMIC/workflows/VariantCalling_sentieon
=> cnvkit for WGS runs

BALSAMIC/snakemake_rules/variant_calling/cnvkit_paired.rule, BALSAMIC/snakemake_rules/variant_calling/cnvkit_single.rule
- Simplifies cnvkit rules for wgs and targetted
- Fixes a bug where snakemake can't use "run" within singularity container
=> Cnvkit singularity fix

BALSAMIC/snakemake_rules/variant_calling/cnvkit_paired.rule, BALSAMIC/snakemake_rules/variant_calling/cnvkit_single.rule, CHANGELOG.md
- Removes unused output files from cnvkit rules
=> Cnvkit cleanup

BALSAMIC/containers/Dockerfile.latest
- adds dockerfile for balsamic as part of ci
=> balsamic dockerized

CHANGELOG.md, README.rst, doc/cli.rst, doc/install.rst, doc/user_guide.rst, install.sh
- Updates documentation for install, README, and cli
- Adds pulling latest balsamic container from Docker
=> Feat: update documentation

BALSAMIC/snakemake_rules/variant_calling/germline.rule, BALSAMIC/snakemake_rules/variant_calling/somatic_tumor_normal.rule, BALSAMIC/snakemake_rules/variant_calling/somatic_tumor_only.rule, BALSAMIC/workflows/VariantCalling
- Sentieon variant callers (TNhaplotyper - Somatic, DNAscope - Germline) added for WES or Targeted panel workflow
=> Sentieon callers for WES

BALSAMIC/config/cluster.json, CHANGELOG.md
- increases time for indel realign and base recalib
=> Increase time scheduler

BALSAMIC/snakemake_rules/quality_control/picard_wgs.rule, BALSAMIC/snakemake_rules/sentieon/sentieon_qc_metrics.rule, CHANGELOG.md
- Quick fix for 
- picard CollectMultipleMetrics
- sentieon WGS metrics
=> Fix: QC rules for WGS pipeline

BALSAMIC/commands/plugins/base.py, BALSAMIC/commands/plugins/deliver.py, BALSAMIC/config/cluster_minimal.json, BALSAMIC/snakemake_rules/annotation/vep.rule, BALSAMIC/utils/cli.py, BALSAMIC/workflows/VariantCalling, CHANGELOG.md, tests/commands/plugins/test_deliver.py, tests/commands/test_cli.py, tests/conftest.py, tests/utils/test_utils.py
- renames housekeeper to deliver
- add vep tab file to list of output files
=> delivery plugin

BALSAMIC/snakemake_rules/annotation/vep.rule
=> Add ontology to vep rule

BALSAMIC/commands/plugins/base.py, BALSAMIC/commands/plugins/cov_plot.py, BALSAMIC/commands/plugins/target_cov.py, CHANGELOG.md
- a plugin command to plot coverage for target regions
=> This PR adds target coverage plugin

BALSAMIC/config/cluster_minimal.json, BALSAMIC/snakemake_rules/variant_calling/cnvkit_paired.rule, BALSAMIC/snakemake_rules/variant_calling/cnvkit_single.rule, BALSAMIC/workflows/GenerateRef, CHANGELOG.md, tests/test_data/references/reference.json
=> update cluster_config and cnvkit files

BALSAMIC/snakemake_rules/variant_calling/split_bed.rule, BALSAMIC/workflows/GenerateRef, CHANGELOG.md, tests/test_data/references/reference.json
=> Bed paddington 🐻

BALSAMIC/config/analysis.json, BALSAMIC/snakemake_rules/variant_calling/cnvkit_paired.rule, BALSAMIC/snakemake_rules/variant_calling/cnvkit_single.rule, BALSAMIC/workflows/VariantCalling, BALSAMIC/workflows/VariantCalling_sentieon, CHANGELOG.md
=> CNVs as VCF

BALSAMIC/snakemake_rules/quality_control/picard.rule, CHANGELOG.md
=> fix: picard stat file log --> output

BALSAMIC/containers/Dockerfile.latest, BALSAMIC/workflows/VariantCalling, CHANGELOG.md
=> Disable vcfmerge

BALSAMIC/snakemake_rules/annotation/vep.rule, BALSAMIC/snakemake_rules/obsolete_rules/bcftools.rule, BALSAMIC/snakemake_rules/obsolete_rules/collectqc_paired.rule, BALSAMIC/snakemake_rules/obsolete_rules/freebayes.rule, BALSAMIC/snakemake_rules/obsolete_rules/mergetype_paired_umi.rule, BALSAMIC/snakemake_rules/obsolete_rules/mergetype_single_umi.rule, BALSAMIC/snakemake_rules/obsolete_rules/pindel_single.rule, BALSAMIC/snakemake_rules/quality_control/GATK.rule, BALSAMIC/snakemake_rules/quality_control/contest.rule, BALSAMIC/snakemake_rules/quality_control/picard.rule, BALSAMIC/snakemake_rules/quality_control/picard_wgs.rule, BALSAMIC/snakemake_rules/quality_control/sambamba_depth.rule, BALSAMIC/snakemake_rules/variant_calling/germline.rule, BALSAMIC/snakemake_rules/variant_calling/mergetype.rule, BALSAMIC/snakemake_rules/variant_calling/mergetype_tumor.rule, BALSAMIC/snakemake_rules/variant_calling/somatic_sv_tumor_normal.rule, BALSAMIC/snakemake_rules/variant_calling/somatic_sv_tumor_only.rule, BALSAMIC/snakemake_rules/variant_calling/somatic_tumor_normal.rule, BALSAMIC/snakemake_rules/variant_calling/somatic_tumor_only.rule, CHANGELOG.md
=> QoL conda in rules

.bumpversion.cfg, BALSAMIC/containers/Dockerfile.latest, BALSAMIC/containers/Dockerfile.release
- Adds container release definition
=> A bit more proper container release definition

BALSAMIC/config/cluster.json, BALSAMIC/snakemake_rules/variant_calling/mergetype.rule, CHANGELOG.rst
=> feat, bam to cram

.github/CODEOWNERS
=> Add Ashwini as co-codeowner

BALSAMIC/conda/BALSAMIC-py36.yaml, BALSAMIC/config/balsamic_env.yaml, CHANGELOG.rst
=> Update conda and container

CHANGELOG.rst, install.sh
- fix the correct latest tag in install script
=> fix, install tag in changelog

BALSAMIC/config/cluster_minimal.json, BALSAMIC/snakemake_rules/quality_control/mosdepth.rule, BALSAMIC/snakemake_rules/quality_control/multiqc.rule, BALSAMIC/workflows/Alignment, BALSAMIC/workflows/VariantCalling, CHANGELOG.rst
- Adds mosdepth rule to calculate coverage
=> region and base coverage rule 

BALSAMIC/config/cluster_minimal.json, BALSAMIC/snakemake_rules/variant_calling/mergetype_tumor.rule
- adds bam to cram for tumor_only mode
=> feat, tumor only bam to cram

BALSAMIC/snakemake_rules/annotation/vep.rule, BALSAMIC/workflows/VariantCalling, CHANGELOG.rst
- This PR annotates germline callers for WES/Panel runs
=> Annotate germline callers

BALSAMIC/snakemake_rules/quality_control/fastp.rule, BALSAMIC/snakemake_rules/quality_control/multiqc.rule, BALSAMIC/workflows/Alignment, BALSAMIC/workflows/VariantCalling, CHANGELOG.rst
=> Make fastp explicitly cuts adapters for PE

BALSAMIC/config/cluster.json, CHANGELOG.rst
=> Time allocation 1

BALSAMIC/snakemake_rules/quality_control/picard.rule, CHANGELOG.rst
=> Bait set name in hsmetric

.github/CODEOWNERS
This PR adds Maria as codeowner for all *py files.
=> add maria as codeowner for all .py files

BALSAMIC/conda/BALSAMIC-py36.yaml, BALSAMIC/snakemake_rules/annotation/vep.rule, BALSAMIC/snakemake_rules/variant_calling/somatic_tumor_only.rule, CHANGELOG.rst
- A temporary solution for https://github.com/Clinical-Genomics/Cancer-project/issues/51 until VarDict's patch comes through.
=> Enable SV calls for VarDict tumor only

requirements-dev.txt
- Freezes version for pytest-cov for travis to work properly
=> freeze version for pytest-cov

.travis.yml, requirements.txt, run_validate.sh
- facilitates to test balsamic cli for case config and run analysis
=> run example cli through travis to test workflow

BALSAMIC/commands/config/case.py, BALSAMIC/snakemake_rules/annotation/varcaller_filter.rule, BALSAMIC/utils/constants.py, BALSAMIC/utils/models.py, tests/utils/test_models.py
Changes in BALSAMIC.utils.models
- Adds additional field validation to some of the models 
- Add unit tests for models where applicable
=> Create tests for models

BALSAMIC/commands/report/deliver.py
- Work directory as path in delivery report
=> fix, workdir as path

.github/PULL_REQUEST_TEMPLATE.md
Changed: simplify pull request template
=> refactor pr template

BALSAMIC/commands/config/case.py, BALSAMIC/commands/run/analysis.py, BALSAMIC/utils/models.py
Fixed: Bind path is not added as None if analysis type is wgs
=> Panel bind path fix

CHANGELOG.rst
=> Release 4.5.0

requirements.txt
Added: pygments added to requirements.txt
=> Add pygments as BALSAMIC dependency

BALSAMIC/snakemake_rules/annotation/vep.rule
Fixed: wildcard error in vep_germline
=> fix wildcard in germline annotation

.github/CODEOWNERS, README.rst
=> update contributor and codeowner

BALSAMIC/commands/report/deliver.py
MINOR FIX
Fixes bug: file was missing from deliverable report if it has index.
=> Fix bug where file missing from report if indexed

BALSAMIC/config/cluster.json
Fixed: failed analysis run time for #370 #367 #366
=> increase analsyis run time for various tools

BALSAMIC/commands/report/deliver.py, BALSAMIC/snakemake_rules/annotation/varcaller_filter.rule, BALSAMIC/snakemake_rules/annotation/vep.rule, BALSAMIC/snakemake_rules/quality_control/fastp.rule, BALSAMIC/snakemake_rules/quality_control/multiqc.rule, BALSAMIC/snakemake_rules/sentieon/sentieon_alignment.rule, BALSAMIC/snakemake_rules/variant_calling/cnvkit_paired.rule, BALSAMIC/snakemake_rules/variant_calling/cnvkit_single.rule, BALSAMIC/snakemake_rules/variant_calling/mergetype.rule, BALSAMIC/snakemake_rules/variant_calling/mergetype_tumor.rule, BALSAMIC/utils/rule.py
Changed: tags for housekeeper delivery
=> refactor, housekeeper tags and simplification

BALSAMIC/snakemake_rules/quality_control/GATK.rule, BALSAMIC/snakemake_rules/variant_calling/germline.rule, BALSAMIC/snakemake_rules/variant_calling/mergetype.rule, BALSAMIC/snakemake_rules/variant_calling/mergetype_tumor.rule, BALSAMIC/snakemake_rules/variant_calling/somatic_tumor_normal.rule, BALSAMIC/snakemake_rules/variant_calling/somatic_tumor_only.rule
Removed: IndelRealigner in preparation for GATK4
=> Deprecate indelrealigner

CHANGELOG.rst
=> Release 5.1.0

.travis.yml, BALSAMIC/conda/balsamic.yaml, requirements.txt
**### This PR:**
Remove cyvcf2 and Cython from `.travis.yml` and adds those dependencies to `requirements.txt` 
Remove conda dependencies for cyvcf2 from `BALSAMIC/conda/balsamic.yaml`
**Problem:**
Removal of `pip install cython and cyvcf2` from `.travis.yml` results in travis build failure
**Solution:**
=> adding cyvcf2 and cython to requirements

BALSAMIC/commands/config/case.py, BALSAMIC/commands/plugins/base.py, BALSAMIC/commands/report/deliver.py, tests/commands/config/test_config_sample.py, tests/commands/plugins/conftest.py, tests/commands/plugins/test_vcfutils_createvcf.py, tests/commands/report/test_deliver.py, tests/conftest.py, tests/utils/test_models.py
Refactor: reformat all the .py files
=> Format all *py files

BALSAMIC/snakemake_rules/align/bwa_mem.rule, BALSAMIC/snakemake_rules/align/sentieon_alignment.rule, BALSAMIC/snakemake_rules/quality_control/picard.rule, BALSAMIC/snakemake_rules/quality_control/sentieon_qc_metrics.rule, BALSAMIC/snakemake_rules/umi/sentieon_consensuscall.rule, BALSAMIC/snakemake_rules/umi/sentieon_umiextract.rule, BALSAMIC/snakemake_rules/umi/sentieon_varcall_tnscope.rule, BALSAMIC/snakemake_rules/variant_calling/germline.rule, BALSAMIC/snakemake_rules/variant_calling/sentieon_germline.rule, BALSAMIC/snakemake_rules/variant_calling/sentieon_t_varcall.rule, BALSAMIC/snakemake_rules/variant_calling/sentieon_tn_varcall.rule, BALSAMIC/snakemake_rules/variant_calling/somatic_tumor_normal.rule, BALSAMIC/snakemake_rules/variant_calling/somatic_tumor_only.rule, BALSAMIC/workflows/balsamic.smk
Changed:
- Refactored align/*.rules to make it more readable.
- Picard's MarkDuplicate is now part of bwa_mem rule
=> Refactor rules: align rules

BALSAMIC/utils/constants.py, BALSAMIC/utils/models.py, BALSAMIC/utils/rule.py, BALSAMIC/workflows/reference.smk
Refactor:
- Do no gzip gnomad vcf.bgz file
=> Refactor/no gunzip gnomad, keep az bgzip

BALSAMIC/assets/vcfanno/vcfanno.toml, BALSAMIC/snakemake_rules/annotation/varcaller_filter.rule, BALSAMIC/snakemake_rules/annotation/vep.rule, BALSAMIC/utils/constants.py, BALSAMIC/utils/models.py, MANIFEST.in, setup.py, tests/test_data/references/reference.json, tests/utils/test_models.py
Added:
- annotate somatic variants with gnomad
Changed:
- extend fitlers for pop_freq using gnomad maxaf
=> annotate with gnomad_genome

BALSAMIC/commands/run/analysis.py
(If this is a release PR, no need to add following. Leave this part empty)
(Use the following lines to create a PR text body. Make sure to remove all non-relevant one after you're done)
(Repeat each field as many times as necessary)
Added: for new features.
Changed: for changes in existing functionality.
Deprecated: for soon-to-be removed features.
Removed: for now removed features.
Fixed: for any bug fixes.
Security: in case of vulnerabilities.
=> create yaml file from jobids in resultpath

BALSAMIC/conda/varcall_py27.yaml
Changed:
- Updated manta to 1.6.0
=> update manta to 1.6.0

BALSAMIC/config/cluster.json, BALSAMIC/snakemake_rules/umi/annotate_vep.rule, BALSAMIC/snakemake_rules/umi/generate_AF_tables.rule, BALSAMIC/snakemake_rules/umi/qc_umi.rule, BALSAMIC/snakemake_rules/umi/sentieon_consensuscall.rule, BALSAMIC/snakemake_rules/umi/sentieon_umiextract.rule, BALSAMIC/snakemake_rules/umi/sentieon_varcall_tnscope.rule, BALSAMIC/snakemake_rules/umi/varcall_vardict.rule, BALSAMIC/utils/constants.py, BALSAMIC/utils/models.py, BALSAMIC/workflows/UMIworkflow.smk, requirements.txt, tests/utils/test_models.py
**Fixed**
**Removed**
**Added**
=> Feat:refactor umirules

BALSAMIC/config/cluster.json
Fixed:
- Increased run time for cnvkit from 8 hour to 10hours fixes #476
=> increase cnvkit queue time request from 8hour, 10 core to 10hour 10 core

BALSAMIC/commands/config/case.py, BALSAMIC/snakemake_rules/quality_control/fastp.rule
Fixed:
- Disable UMI trimming attempt for WGS workflow
=> Disable UMI trim option for  WGS

BALSAMIC/commands/run/analysis.py, BALSAMIC/commands/run/scheduler.py, BALSAMIC/config/cluster.json, BALSAMIC/config/cluster_minimal.json, BALSAMIC/snakemake_rules/dragen_suite/dragen_dna.rule, BALSAMIC/utils/cli.py, BALSAMIC/workflows/balsamic.smk, tests/commands/run/test_run_analysis.py, tests/commands/run/test_scheduler.py
Added:
- `--dragen` option to `balsamic run analysis` for tumor only WGS runs
=> DRAGEN addition

CHANGELOG.rst
=> release 6.0.2

CHANGELOG.rst
=> Release 6.0.3

BALSAMIC/containers/align_qc/align_qc.yaml
Changed:
- FastQC bumped to 0.11.9
=> fastqc version bump

CHANGELOG.rst
=> Release 6.0.4

BALSAMIC/commands/config/case.py, BALSAMIC/snakemake_rules/annotation/rankscore.rule, BALSAMIC/snakemake_rules/annotation/varcaller_filter_tumor_normal.rule, BALSAMIC/snakemake_rules/annotation/varcaller_filter_tumor_only.rule, BALSAMIC/utils/constants.py, BALSAMIC/utils/models.py, BALSAMIC/workflows/balsamic.smk, BALSAMIC/workflows/reference.smk, run_validate.sh, tests/commands/config/test_config_sample.py, tests/conftest.py, tests/utils/test_utils.py
Added:
- rankscore init file as reference
- rankscore rule to rank tumor-normal and tumor-only panel variants
=> rankscore for genmod as reference and rule

CHANGELOG.rst
=> Release 6.1.0

MANIFEST.in, requirements.txt, setup.py
Fixed:
- Missing template to QC template report
=> add missing template to included files

BALSAMIC/snakemake_rules/annotation/varcaller_wgs_filter_tumor_normal.rule, BALSAMIC/workflows/balsamic.smk
Adds bcftools filters for wgs TN cases for TNscope results
=> TN wgs filters for tnscope

BALSAMIC/containers/annotate/annotate.sh
Changed:
- bumped genmod version to 3.7.4 fixes #561
=> bump genmod

CHANGELOG.rst
=> release 6.1.2

BALSAMIC/snakemake_rules/variant_calling/somatic_sv_tumor_normal.rule, BALSAMIC/snakemake_rules/variant_calling/somatic_sv_tumor_only.rule
Fixed:
- A bug in Manta variant calling rules that didn't name samples properly to TUMOR/NORMAL in the VCF file
=> fixes #571

.bumpversion.cfg
Fixes unused file from bumpversion config.
=> remove unused file from bumpversion config

.github/workflows/docker_build_push.yml, .github/workflows/docker_build_push_release.yml, .github/workflows/docker_build_test.yml
- Add a new workflow for release
=> Fix workflow docker release

CHANGELOG.rst
=> merge release into develop

BALSAMIC/commands/config/case.py, BALSAMIC/snakemake_rules/umi/mergetype_normal_umi.rule, BALSAMIC/snakemake_rules/umi/mergetype_tumor_umi.rule, BALSAMIC/snakemake_rules/umi/mergetype_umi.rule, BALSAMIC/snakemake_rules/umi/sentieon_varcall_tnscope.rule, BALSAMIC/snakemake_rules/umi/sentieon_varcall_tnscope_tn.rule, BALSAMIC/utils/models.py, BALSAMIC/workflows/UMIworkflow.smk, BALSAMIC/workflows/balsamic.smk, CHANGELOG.rst, tests/utils/test_models.py
Small add-on changes to the umiworkflow.
Fixed:
- Set  umi_workflow: true for panel  else false in config json
- Remove duplicate umiworkflow attribute in models.py
- Rename the umiconsensus bam headers from {samplenames} to TUMOR/NORMAL.
=> hotfix 7.1.2 umiworkflow small fixes

.readthedocs.yml, CHANGELOG.rst, docs/README.rst
Fixed:
- failing doc build due to updating requirements.txt
=> Hotfix documentation

BALSAMIC/commands/run/analysis.py, CHANGELOG.rst
Fixed:
- Fixes #590 for incorrect binding path
=> Fix/vcfanno bind path 

BALSAMIC/utils/constants.py, CHANGELOG.rst
Changed:
- Updated download URL for 1kg from ftp to http. (FTP seemed to be unstable and constantly broke)
=> Fix: Update download url from ftp to http

BALSAMIC/assets/report_template/balsamic_report.html
- adds a css style to page so it's exported correctly as PDF in Scout, see [this issue](https://github.com/Clinical-Genomics/scout/issues/2442)
=> Add page lansdcape orientation CSS style to report, so it's exported correctly as PDF

.github/workflows/dont_forget_changelog.yml, CHANGELOG.rst
Added:
- changelog reminder Github workflow
=> changelog reminder

BALSAMIC/containers/align_qc/align_qc.yaml, BALSAMIC/snakemake_rules/align/sentieon_alignment.rule, BALSAMIC/snakemake_rules/annotation/varcaller_filter_tumor_normal.rule, BALSAMIC/snakemake_rules/annotation/varcaller_filter_tumor_only.rule, BALSAMIC/snakemake_rules/annotation/varcaller_wgs_filter_tumor_normal.rule, BALSAMIC/snakemake_rules/annotation/varcaller_wgs_filter_tumor_only.rule, BALSAMIC/snakemake_rules/annotation/vep.rule, BALSAMIC/utils/cli.py, BALSAMIC/workflows/UMIworkflow.smk, BALSAMIC/workflows/balsamic.smk, CHANGELOG.rst, tests/test_data/vcf_tables/test_createVCF_output.vcf.gz, tests/utils/test_utils.py
Changed:
- only pass variants are not part of delivery anymore
- delivery tag file ids are properly matched with sample_name
Removed:
- sentieon-dedup rule from delivery
=> Hotfix - simplify delivery and correct file id

.github/workflows/docker_build_push_develop.yml, .github/workflows/docker_build_push_master.yml, .github/workflows/docker_build_push_release.yml, .github/workflows/docker_build_test_pull_request.yml, .github/workflows/pytest_and_coveralls.yml, CHANGELOG.rst, README.rst
Changed:
- Github actions workflow names updated to reflect the content properly
=> Fix readme and workflow badges

BALSAMIC/snakemake_rules/umi/sentieon_consensuscall.rule, BALSAMIC/snakemake_rules/umi/sentieon_umiextract.rule, BALSAMIC/workflows/UMIworkflow.smk, BALSAMIC/workflows/balsamic.smk, CHANGELOG.rst
Fixed:
- An error with Sentieon for better management of memory fixes #621
=> Fix: mem options for sentieon

.github/workflows/docker_build_push_develop.yml, .github/workflows/docker_build_push_master.yml, .github/workflows/docker_build_push_release.yml, .github/workflows/docker_build_test_pull_request.yml, BALSAMIC/config/balsamic_env.yaml, BALSAMIC/containers/varcall_delly/varcall_delly.sh, BALSAMIC/containers/varcall_delly/varcall_delly.yaml, BALSAMIC/containers/varcall_py36/varcall_py36.yaml, BALSAMIC/snakemake_rules/variant_calling/somatic_sv_tumor_normal.rule, BALSAMIC/utils/constants.py, CHANGELOG.rst
=> Feat/add Delly container

.github/workflows/pytest_and_coveralls.yml, CHANGELOG.rst
Changed:
- Do not run pytest actions on changelog or docs update
=> Avoid running pytest when changelog or docs are updated

BALSAMIC/containers/annotate/annotate.yaml, CHANGELOG.rst, Dockerfile
Added:
- `git` to Dockerfile definition
=> add git to containers

BALSAMIC/config/balsamic_env.yaml, BALSAMIC/containers/varcall_cnvkit/varcall_cnvkit.yaml, CHANGELOG.rst
Install R package and its dependencies into the same container as cnvkit
=> add purecn dependencies

BALSAMIC/snakemake_rules/variant_calling/cnvkit_single.rule, BALSAMIC/workflows/balsamic.smk, CHANGELOG.rst
By mistake I pushed my recent code on refactoring cnvkit command to develop branch directly
Related commits are:  7b648dde7d6ffe90155afc775aa98f1d261eed00 and afc17e50f385e5d25e96644779a4c8d37812a458
Issue related to https://github.com/Clinical-Genomics/cgp-cancer-cnvcall/issues/15
=> cnvkit refactor changelog

BALSAMIC/utils/constants.py, CHANGELOG.rst
=> Update GNOMAD URL [Issue 664]

.github/CODEOWNERS
Add Khurram to code owners in develop
=> Update CODEOWNERS develop

BALSAMIC/snakemake_rules/umi/sentieon_consensuscall.rule, CHANGELOG.rst
Changed:
- Updated Sentieon util sort to match with version 20201002
=> Hotfix/ updated sentieon util sort 20201002

BALSAMIC/snakemake_rules/annotation/vep.rule, CHANGELOG.rst
Updates:
- Improves TMB calculation for panelseq data
=> Optimize TMB calculation

BALSAMIC/utils/constants.py, CHANGELOG.rst
Changed:
- Bumped cosmic version 94 and a valid path
=> Hotfix/ bump cosmic to v94

BALSAMIC/config/analysis.json, BALSAMIC/config/cluster.json, BALSAMIC/containers/ascatngs/ascatngs.sh, BALSAMIC/containers/ascatngs/ascatngs.yaml, BALSAMIC/snakemake_rules/variant_calling/somatic_sv_tumor_normal.rule, BALSAMIC/utils/constants.py, BALSAMIC/utils/models.py, BALSAMIC/workflows/balsamic.smk, CHANGELOG.rst
Added: ascat tumor normal rule.
=> Add ascat tumor normal rule

BALSAMIC/workflows/reference.smk, CHANGELOG.rst
Related to https://github.com/Clinical-Genomics/BALSAMIC/issues/704
=> fix space in reference json

.github/workflows/conventional_pr.yml, CHANGELOG.rst, docs/git_etiquette.rst
Added:
- Conventional PR GitHub workflow and updated docs accordingly
=> feat: adds a check on pr title

BALSAMIC/workflows/reference.smk, CHANGELOG.rst
Changed:
- Missing date added to reference.json file #456
=> fix: add access date to reference file

CHANGELOG.rst, docs/FAQs.rst
=> docs: update git FAQs

BALSAMIC/utils/constants.py, CHANGELOG.rst
Added: ascatngs hg38 reference files.
=> feat: ascatngs hg38 references

BALSAMIC/containers/varcall_py36/varcall_py36.sh, CHANGELOG.rst
Fixed: softlink for libreadline.so in varcall_py36
=> fix: softlink for libreadline.so in varcall_py36

BALSAMIC/assets/vcfanno/vcfanno.toml, BALSAMIC/utils/constants.py, BALSAMIC/utils/models.py, BALSAMIC/workflows/reference.smk, CHANGELOG.rst, tests/conftest.py, tests/test_data/references/reference.json
Added:
- ClinVar as a source of annotation. fixes #737
=> feat: add clinvar as a source of annotation

CHANGELOG.rst, Dockerfile
Fixes the pip install misbehaviour of balsamic inside its container.
=> fix: pip install inside balsamic container

CHANGELOG.rst
Fixed changelog that I forgot to push in pr #759
=> fix: changelog from pr 759

BALSAMIC/workflows/PON.smk, BALSAMIC/workflows/reference.smk, CHANGELOG.rst
=> refactor: Remove activating environments from reference,PON workflows

BALSAMIC/snakemake_rules/variant_calling/somatic_sv_tumor_normal.rule, BALSAMIC/snakemake_rules/variant_calling/somatic_sv_tumor_only.rule, CHANGELOG.rst
Fixed: input bam files for SV rules.
=> fix: issue 765 input bamfiles for SV rules

BALSAMIC/snakemake_rules/variant_calling/germline.rule, BALSAMIC/snakemake_rules/variant_calling/somatic_sv_tumor_normal.rule, BALSAMIC/snakemake_rules/variant_calling/somatic_sv_tumor_only.rule, CHANGELOG.rst
=> fix: wrong install paths

BALSAMIC/snakemake_rules/umi/mergetype_normal_umi.rule, BALSAMIC/snakemake_rules/umi/mergetype_tumor_umi.rule, BALSAMIC/snakemake_rules/umi/qc_umi.rule, BALSAMIC/snakemake_rules/umi/sentieon_consensuscall.rule, BALSAMIC/snakemake_rules/umi/sentieon_umiextract.rule, BALSAMIC/snakemake_rules/umi/sentieon_varcall_tnscope.rule, BALSAMIC/snakemake_rules/umi/sentieon_varcall_tnscope_tn.rule, CHANGELOG.rst
=> fix: multiqc hsmetrics for not capturing all bam outputs

.github/workflows/create_release_from_tag.yml, CHANGELOG.rst, CITATION.cff
Added:
- Create release for Zenodo to be citable
=> feat: Create citable release for Zenodo

BALSAMIC/snakemake_rules/annotation/vep.rule, CHANGELOG.rst
=> fix: redundant line in tmb rule

BALSAMIC/snakemake_rules/quality_control/multiqc.rule, BALSAMIC/snakemake_rules/umi/qc_umi.rule, CHANGELOG.rst
Fixes : #844 
**Tests:**
`/home/proj/long-term-stage/cancer/UMI_analysis_runs_APJ/cancer_test_datasets/panel_TN/stablevaren_testqc/analysis/qc/multiqc_data/multiqc_picard_dups.json`
=> feat: report umi duplication rate

BALSAMIC/assets/scripts/collect_qc_metrics.py, CHANGELOG.rst, tests/scripts/test_collect_qc_metrics.py
Fixes ``collect_qc_metrics.py`` crash for WGS cases with empty ``capture_kit`` argument.
=> fix: capture kit empty argument for WGS runs

BALSAMIC/containers/balsamic/Dockerfile, BALSAMIC/containers/balsamic/balsamic.yaml, BALSAMIC/snakemake_rules/variant_calling/somatic_tumor_only.rule, BALSAMIC/utils/scheduler.py, CHANGELOG.rst
Fixes #856 
Fixes spell for `abspath`
=> fix: slurm qos

BALSAMIC/config/cluster.json, BALSAMIC/constants/workflow_params.py, BALSAMIC/containers/annotate/annotate.yaml, BALSAMIC/snakemake_rules/annotation/vep.rule, CHANGELOG.rst
Fixed:  cluster configuration for vep rules #857
=> fix: optimize vep

BALSAMIC/config/balsamic_env.yaml, BALSAMIC/constants/common.py, BALSAMIC/constants/workflow_params.py, BALSAMIC/containers/varcall_py36/varcall_py36.yaml, CHANGELOG.rst, container_tests/varcall_py36/varcall_py36.sh, docs/resources.rst, tests/test_data/BALSAMIC_env.yaml
(If this is a release PR, no need to add following. Leave this part empty)
(Use the following lines to create a PR text body. Make sure to remove all non-relevant one after you're done)
(Repeat each field as many times as necessary)
Added: SVDB to varcall_py36 container.
=> feat: add SVDB

BALSAMIC/constants/workflow_rules.py, BALSAMIC/snakemake_rules/umi/mergetype_normal_umi.rule, BALSAMIC/snakemake_rules/umi/mergetype_tumor_umi.rule, BALSAMIC/snakemake_rules/umi/sentieon_consensuscall.rule, CHANGELOG.rst
Added: Generates CRAM files from UMI-consensus called bam files. Related to #865
=> feat: generate umi cram files

.github/workflows/sphinx_docs.yml, .readthedocs.yml, CHANGELOG.rst, docs/README.rst, docs/requirements.txt
=> docs: update docutils

BALSAMIC/config/analysis.json, BALSAMIC/config/cluster.json, BALSAMIC/snakemake_rules/annotation/varcaller_sv_wgs_filter_tumor_normal.rule, BALSAMIC/snakemake_rules/annotation/varcaller_sv_wgs_filter_tumor_only.rule, BALSAMIC/snakemake_rules/variant_calling/somatic_sv_tumor_normal.rule, BALSAMIC/snakemake_rules/variant_calling/somatic_sv_tumor_only.rule, BALSAMIC/utils/models.py, CHANGELOG.rst
=> feat: add svdb workflow

.bumpversion.cfg, CHANGELOG.rst, docs/balsamic_filters.rst, docs/install.rst
- The BALSAMIC install version is hardcoded in https://balsamic.readthedocs.io/en/latest/install.html
- Fix automation for this install page in bumpversion 
- Add more text about TNscope-umi pre-call settings to https://balsamic.readthedocs.io/en/latest/balsamic_filters.html
=> docs: fix version and doc text

.github/workflows/black_linter.yml, BALSAMIC/commands/init/base.py, BALSAMIC/commands/run/analysis.py, CHANGELOG.rst, requirements-dev.txt
Added: New slurm qos tag `express`.
Fixes #885 
Tested on stage in dry-run:
``
=> fix: qos express

.github/workflows/black_linter.yml, BALSAMIC/containers/varcall_py36/varcall_py36.yaml, CHANGELOG.rst
Changed: updated svdb to 2.6.0
=> fix: update svdb to 2.6.0

BALSAMIC/containers/annotate/annotate.yaml, BALSAMIC/containers/balsamic/Dockerfile, CHANGELOG.rst, container_tests/annotate/annotate.sh
=> fix: bcftools locked in annotate container

BALSAMIC/snakemake_rules/variant_calling/somatic_sv_tumor_normal.rule, CHANGELOG.rst, requirements-dev.txt
Added: ascatNGS copynumber file
=> feat: add ascatngs copynumber

CHANGELOG.rst
As per the suggestion from https://github.com/Clinical-Genomics/validations/pull/34#discussion_r873446656
Also, in the future, it's best practice to add URL links to the changelog instead of just issue or PR numbers.
=> docs: Update CHANGELOG.rst with urls

.github/workflows/pytest_and_coveralls.yml, CHANGELOG.rst
(If this is a release PR, no need to add following. Leave this part empty)
(Use the following lines to create a PR text body. Make sure to remove all non-relevant one after you're done)
(Repeat each field as many times as necessary)
Added: for new features.
Changed: for changes in existing functionality.
Deprecated: for soon-to-be removed features.
Removed: for now removed features.
Fixed: for any bug fixes.
Security: in case of vulnerabilities.
=> fix: codecov v2

CHANGELOG.rst, docs/balsamic_methods.rst, docs/bioinfo_softwares.rst
Added: SV and CNV analysis and TIDDIT to Readthedocs
Changed: delly version in Readthedocs
=> feat: Update balsamic Readthedocs

BALSAMIC/commands/config/case.py, BALSAMIC/commands/config/pon.py, BALSAMIC/constants/common.py, BALSAMIC/constants/workflow_rules.py, BALSAMIC/snakemake_rules/annotation/vcf2cytosure_convert.rule, BALSAMIC/snakemake_rules/variant_calling/cnvkit_paired.rule, BALSAMIC/snakemake_rules/variant_calling/cnvkit_single.rule, BALSAMIC/snakemake_rules/variant_calling/somatic_sv_tumor_normal.rule, BALSAMIC/utils/models.py, CHANGELOG.rst, run_validate.sh, tests/commands/config/test_config_pon.py, tests/commands/config/test_config_sample.py, tests/utils/test_models.py
- Adds provided gender to config file
- Updates following rules including the provided gender as an input:
- `vcf2cytosure_convert` (TO-PANEL)
- `vcf2cytosure_convert_tumor_only`, `vcf2cytosure_convert_tumor_normal` (WGS)
- `cnvkit_single`, `cnvkit_paired` (PANEL)
- `ascat_tumor_normal` (TN-WGS)
=> feat: Add provided gender to config file & update rules

BALSAMIC/containers/annotate/annotate.sh, BALSAMIC/containers/annotate/annotate.yaml, BALSAMIC/containers/varcall_py3/varcall_py3.sh, BALSAMIC/snakemake_rules/annotation/varcaller_filter_tumor_normal.rule, BALSAMIC/snakemake_rules/annotation/varcaller_filter_tumor_only.rule, CHANGELOG.rst
=> fix: cyvcf2 in varcallpy3 container

BALSAMIC/containers/vcf2cytosure/Dockerfile, BALSAMIC/containers/vcf2cytosure/vcf2cytosure.sh, BALSAMIC/containers/vcf2cytosure/vcf2cytosure.yaml, BALSAMIC/snakemake_rules/annotation/vcf2cytosure_convert.rule, CHANGELOG.rst, container_tests/vcf2cytosure/vcf2cytosure.sh, docs/index.rst, docs/resources.rst
Added: tabix and gzip to vcf2cytosure container
=> feat: add tabix and gzip to vcf2cytosure container

BALSAMIC/config/cluster.json, BALSAMIC/snakemake_rules/variant_calling/somatic_sv_tumor_normal.rule, BALSAMIC/snakemake_rules/variant_calling/somatic_sv_tumor_only.rule, BALSAMIC/workflows/balsamic.smk, CHANGELOG.rst, docs/balsamic_methods.rst, docs/balsamic_sv_cnv.rst, docs/cli_package.rst
Fixed: Command and condition for TIDDIT and fixed ReadtheDocs
=> fix: command and condition for tiddit and fixed ReadtheDocs

BALSAMIC/containers/varcall_cnvkit/varcall_cnvkit.yaml, CHANGELOG.rst
Changed: missing R packages to cnvkit container
=> fix: add missing R pachages to cnvkit container

BALSAMIC/containers/varcall_cnvkit/varcall_cnvkit.yaml, CHANGELOG.rst
Added: rlang to cnvkit container.
=> fix: rlang to cnvkit conatainer

.github/workflows/black_linter.yml, .github/workflows/conventional_pr.yml, .github/workflows/create_release_from_tag.yml, .github/workflows/docker_build_push.yml, .github/workflows/docker_build_push_release.yml, .github/workflows/docker_build_push_release_submodules.yml, .github/workflows/docker_build_push_submodules.yml, .github/workflows/docker_build_test_pull_request.yml, .github/workflows/docker_build_test_pull_request_submodules.yml, .github/workflows/dont_forget_changelog.yml, .github/workflows/pytest_and_coveralls.yml, .github/workflows/sphinx_docs.yml, BALSAMIC/containers/vcf2cytosure/Dockerfile, BALSAMIC/containers/vcf2cytosure/vcf2cytosure.yaml, CHANGELOG.rst, setup.py
Updates `vcf2cytosure` version to v0.8  & GitHub actions image
=> perf: Update vcf2cytosure version & GitHub actions image

BALSAMIC/snakemake_rules/variant_calling/mergetype_normal.rule, BALSAMIC/snakemake_rules/variant_calling/mergetype_tumor.rule, BALSAMIC/workflows/balsamic.smk, CHANGELOG.rst
Added: samtools index command.
Changed: Annotation names for swegen.
=> refactor: Annotation names and  add samtools index command

BALSAMIC/constants/workflow_params.py, BALSAMIC/snakemake_rules/annotation/vep.rule, BALSAMIC/snakemake_rules/quality_control/qc_metrics.rule, BALSAMIC/utils/models.py, CHANGELOG.rst, tests/conftest.py, tests/utils/test_utils.py
* Extract number of variants from clinical files 
* If statement in `vep_somatic_clinical_snv` rule
* `TNhaplotyper` for TGS
=> fix: shell condition & remove tnhaplotyper

BALSAMIC/snakemake_rules/annotation/varcaller_filter_tumor_normal.rule, BALSAMIC/snakemake_rules/annotation/varcaller_filter_tumor_only.rule, BALSAMIC/snakemake_rules/annotation/varcaller_wgs_filter_tumor_normal.rule, BALSAMIC/snakemake_rules/annotation/varcaller_wgs_filter_tumor_only.rule, BALSAMIC/snakemake_rules/quality_control/qc_metrics.rule, BALSAMIC/snakemake_rules/umi/sentieon_varcall_tnscope.rule, BALSAMIC/snakemake_rules/umi/sentieon_varcall_tnscope_tn.rule, BALSAMIC/snakemake_rules/variant_calling/sentieon_quality_filter.rule, BALSAMIC/snakemake_rules/variant_calling/somatic_tumor_normal.rule, BALSAMIC/snakemake_rules/variant_calling/somatic_tumor_only.rule, BALSAMIC/workflows/balsamic.smk, CHANGELOG.rst
Added: Research and Clinical VCF for TGA workflow
=> feat: add research and clinical VCF for TGA workflow

BALSAMIC/config/cluster.json, BALSAMIC/constants/workflow_params.py, BALSAMIC/snakemake_rules/variant_calling/mergetype_normal.rule, BALSAMIC/snakemake_rules/variant_calling/mergetype_tumor.rule, CHANGELOG.rst
Fixed: invalid flag for mate and update commands
=> fix: invalid flag for mate and update commands

BALSAMIC/config/cluster.json, BALSAMIC/snakemake_rules/annotation/varcaller_filter_tumor_normal.rule, BALSAMIC/snakemake_rules/annotation/varcaller_filter_tumor_only.rule, BALSAMIC/snakemake_rules/annotation/varcaller_sv_filter.rule, BALSAMIC/snakemake_rules/annotation/varcaller_wgs_filter_tumor_normal.rule, BALSAMIC/snakemake_rules/annotation/varcaller_wgs_filter_tumor_only.rule, BALSAMIC/snakemake_rules/annotation/vcfheader_rename.rule, BALSAMIC/snakemake_rules/annotation/vep.rule, BALSAMIC/snakemake_rules/variant_calling/mergetype_normal.rule, BALSAMIC/snakemake_rules/variant_calling/mergetype_tumor.rule, CHANGELOG.rst
Added: Cluster configuration for the rules with missing cluster configuration and for the newly added rules.
=> feat: add cluster configuration

BALSAMIC/snakemake_rules/variant_calling/mergetype_tumor.rule, CHANGELOG.rst
Fixed: samtools command for mergetype tumor.
=> fix: samtools command for mergetype tumor

BALSAMIC/containers/delly/Dockerfile, BALSAMIC/snakemake_rules/variant_calling/somatic_sv_tumor_normal.rule, BALSAMIC/snakemake_rules/variant_calling/somatic_sv_tumor_only.rule, CHANGELOG.rst, docs/balsamic_methods.rst
Added: New rules delly CNV for TGA, TO and TN workflows.
=> feat: add rules delly cnv for TGA TO and TN workflow

BALSAMIC/containers/varcall_py3/varcall_py3.yaml, BALSAMIC/snakemake_rules/variant_calling/somatic_tumor_normal.rule, BALSAMIC/snakemake_rules/variant_calling/somatic_tumor_only.rule, CHANGELOG.rst, tests/utils/test_utils.py
Fixed: bcftools in varcall_py3
=> fix: varcall_py3 bcftools fail

BALSAMIC/snakemake_rules/variant_calling/somatic_sv_tumor_normal.rule, CHANGELOG.rst
Fixed: Delly command for tumor-normal analysis.
=> fix: delly command for tumor normal analysis

BALSAMIC/config/cluster.json, BALSAMIC/snakemake_rules/variant_calling/sentieon_quality_filter.rule, CHANGELOG.rst
Fixed: tabix command in quality filter tnscope umi rule.
=> fix: bcftools quality filter t nscope umi tumor only rule

.github/CODEOWNERS, CHANGELOG.rst
Sets as code owners the @Clinical-Genomics/cancer-bioinfo team.
=> refactor: CODEOWNERS

.github/workflows/add-to-bl.yml
- Adds a GitHub action which will add all new issues to the Cancer BL project
In the future this could be tweaked so only issues marked with certain labels etc get's added, but I think we can start with all issues
They will be added to the "To Discuss" column.
=> feat: Create add-to-bl.yml

BALSAMIC/snakemake_rules/annotation/varcaller_filter_tumor_normal.rule, BALSAMIC/snakemake_rules/annotation/varcaller_filter_tumor_only.rule, BALSAMIC/snakemake_rules/annotation/varcaller_wgs_filter_tumor_normal.rule, BALSAMIC/snakemake_rules/annotation/varcaller_wgs_filter_tumor_only.rule, CHANGELOG.rst
Fixed: Number of variants increased with inclusion of triallelic_sites
=> fix: Number of variants increased with inclusion of triallelic_sites

.github/ISSUE_TEMPLATE/feature.md, .github/ISSUE_TEMPLATE/feature_request.md
Added: 
- Adds a 'request' label on any new feature requests 
- New issue template for 'features'. To be used when refining a new feature to be planned for release
=> Feature issue template

.github/ISSUE_TEMPLATE/feature.md
Adds a section in the feature issue to keep rack of the origin of the problem
=> Changed: requests solved in feature issue template

BALSAMIC/snakemake_rules/annotation/vep.rule, CHANGELOG.rst
No proper indentation of the if statement. Introduced in https://github.com/Clinical-Genomics/BALSAMIC/pull/1187 
Fixed:
-
=> fix: bash commands in vep_somatic_clinical_snv 

BALSAMIC/snakemake_rules/annotation/vep.rule, CHANGELOG.rst
* Fix SVDB annotation intermediate rule
=> fix: SVDB annotation intermediate rule 

CHANGELOG.rst, docs/bioinfo_softwares.rst
Changed: Version of the tools.
=> docs: update tool versions

.github/workflows/pytest_and_coveralls.yml
Removed:
- Duplicated GitHub actions triggered by push & pull request
=> refactor: Remove duplicated pytest github action

BALSAMIC/models/metrics.py, BALSAMIC/snakemake_rules/umi/concatenation_umi.rule, CHANGELOG.rst, tests/models/test_metric_models.py
-  Restored balsamic container in UMI concatenation rule
=> fix: Restored balsamic container in UMI concatenation rule 

BALSAMIC/constants/metrics.py, CHANGELOG.rst
https://github.com/Clinical-Genomics/BALSAMIC/pull/1265
=> perf: Lower `PCT_PF_READS_IMPROPER_PAIRS` QC threshold to 5%

.github/ISSUE_TEMPLATE/feature.md
- Adds a section in the feature issue as a reminder to not forget any infrastructure changes needed
=> chore: Update feature.md

.github/ISSUE_TEMPLATE/maintenance_task.yml, .github/ISSUE_TEMPLATE/user_story.yml
Added: A User Story issue template using the GitHub issue forms
N/A
=> chore: create user_story issue template

.github/ISSUE_TEMPLATE/user_story.yml
Changed: Updated the user story template
=> chore: re-worked order in user story template

.github/ISSUE_TEMPLATE/user_story.yml
Changed: Added a SOUp field to the user-story template
=> chore: update user_story with SOUP field

.github/workflows/pytest_and_coveralls.yml, BALSAMIC/assets/scripts/csv_to_pdf.py, BALSAMIC/assets/scripts/merge_pdfs.py, BALSAMIC/constants/cluster_analysis.json, BALSAMIC/constants/constants.py, BALSAMIC/constants/rules.py, BALSAMIC/models/config.py, BALSAMIC/snakemake_rules/concatenation/concatenation.rule, BALSAMIC/snakemake_rules/quality_control/report.rule, BALSAMIC/snakemake_rules/scripts/generate_pdf.rule, BALSAMIC/snakemake_rules/scripts/merge_pdfs.rule, BALSAMIC/utils/rule.py, BALSAMIC/workflows/balsamic.smk, CHANGELOG.rst, docs/README.rst, docs/install.rst, setup.py, tests/conftest.py, tests/scripts/test_csv_to_pdf.py, tests/scripts/test_merge_pdf.py, tests/test_data/cnv_report/CNV.somatic.case_id.purecn.purity.csv
* CNV report for TGA workflow
* `wkhtmltopdf` to system requirements
=> feat: TGA CNV report

BALSAMIC/snakemake_rules/annotation/somatic_sv_annotation.rule, CHANGELOG.rst, docs/balsamic_annotation.rst
Fixes https://github.com/Clinical-Genomics/BALSAMIC/issues/1353
=> fix:  Loqusdb SV annotations

.github/ISSUE_TEMPLATE/assessment.yml, .github/ISSUE_TEMPLATE/bug_report.yml
Added: 
- An issue template for assessments
- An issue template for bugs
=> chore: create assessment and bug issue template

BALSAMIC/constants/rules.py, BALSAMIC/constants/workflow_params.py, BALSAMIC/snakemake_rules/misc/sleep.rule, BALSAMIC/snakemake_rules/quality_control/fastp_tga.rule, BALSAMIC/snakemake_rules/quality_control/fastp_wgs.rule, BALSAMIC/snakemake_rules/quality_control/fastqc.rule, BALSAMIC/snakemake_rules/umi/concatenation_umi.rule, BALSAMIC/workflows/PON.smk, BALSAMIC/workflows/QC.smk, BALSAMIC/workflows/balsamic.smk, CHANGELOG.rst
* Sleep rule before start to fix key_error https://github.com/Clinical-Genomics/BALSAMIC/pull/1311
* Missing `__init__.py` in `snakemake_rules` folders https://github.com/Clinical-Genomics/BALSAMIC/pull/1383
| Case ID        | Analysis type      | Test                                     | QoS  | Status    |
|----------------|--------------------|------------------------------------------|----- |-----------|
| `acetuna`      | QC, tumor-only     | Verify no KeyError during job submission | high | Pass |
| `fleetjay`     | WGS, tumor-normal  | Verify no KeyError during job submission | high     | Pass |
| `setamoeba`    | TGA, tumor-only    | Verify no KeyError during job submission | high | Pass |
| `uphippo`      | UMI, tumor-only    | Verify no KeyError during job submission |  high …
=> feat: Release v13.0.1

.gitignore, BALSAMIC/commands/config/case.py, BALSAMIC/commands/options.py, BALSAMIC/models/config.py, BALSAMIC/utils/cli.py, BALSAMIC/workflows/balsamic.smk, CHANGELOG.rst, tests/utils/test_utils.py
> Cancer meeting 2024-06-17:
> - We need to create an argument for UMI settings “1,0,0” or “3,1,1” during config case
- Min reads UMI option to CLI
- <img width="222" alt="Screenshot 2024-06-18 at 17 18 32" src="https://github.com/Clinical-Genomics/BALSAMIC/assets/26309194/bcb043e4-fb9a-4376-91b5-6962558a8e05">
- <img width="222" alt="Screenshot 2024-06-18 at 17 17 41" src="https://github.com/Clinical-Genomics/BALSAMIC/assets/26309194/571ac537-15ad-406d-90c1-2421d7afb4ac">
- <img width="777" alt="Screenshot 2024-06-19 at 09 33 43" src="https://github.com/Clinical-Genomics/BALSAMIC/assets/26309194/dc2430c9-00c9-44b8-b80d-0d5c82d862a0">
- **UMI T/N …
=> feat: Min reads UMI option to CLI

.github/PULL_REQUEST_TEMPLATE.md
This PR is created to adress the deviation: https://github.com/Clinical-Genomics/Deviations/issues/666 which was created due to inclusion of tumor samples and wrong bait-set version prepped samples in the creation of the myeloid PoN. 
These are changes to the PR template to highlight the need to verify that the correct samples are included in the PoN. 
- New steps to the PR template for PoN sample selection verification
- [Screenshot]
<details>
- **Stored files in …
=> chore: update PR template with PON instructions

BALSAMIC/containers/vcf2cytosure/Dockerfile, BALSAMIC/containers/vcf2cytosure/vcf2cytosure.yaml, CHANGELOG.rst, tests/test_data/config.json, tests/test_data/config_pon.json
Updating vcf2cytosure to the latest version
- Upgrade `vcf2cytosure` version to 0.9.1 and remove hardcoded versions
-  <img width="666" alt="Screenshot 2024-06-24 at 16 18 37" src="https://github.com/Clinical-Genomics/BALSAMIC/assets/26309194/1eb63092-a4de-43fd-b2a4-e242b4b926c2">
<details>
</details>
> …
=> chore: Update vcf2cytosure version

BALSAMIC/constants/rules.py, BALSAMIC/snakemake_rules/annotation/msi_tumor_normal.rule, CHANGELOG.rst
Add MSI tumor-normal analysis output to the housekeeper storage.
[PR description]
- MSI tumor normal output to housekeeper storage.
- [Screenshot]
<details>
</details>
- **Tests**
- **Review**
- **Code** …
=> feat: add msi tn to storage

BALSAMIC/containers/msisensorpro/msisensorpro.yaml, BALSAMIC/containers/somalier/Dockerfile, BALSAMIC/containers/somalier/somalier.yaml, CHANGELOG.rst, docs/bioinfo_softwares.rst, tests/test_data/config.json
Updated somalier and fixed the container by updating the dependencies and fixing the versions.
[PR description]
updated somalier to 0.2.19
- Dependencies and versions
- [Screenshot]
<details>
</details>
- …
=> fix: somalier container

BALSAMIC/commands/report/deliver.py, BALSAMIC/models/snakemake.py, CHANGELOG.rst, tests/commands/report/test_deliver.py, tests/conftest.py, tests/models/test_snakemake_models.py
See issue here: https://github.com/Clinical-Genomics/BALSAMIC/issues/1531
2 PRs associated:
- THIS ONE
- Hermes https://github.com/Clinical-Genomics/hermes/pull/133
- case_report.html from delivery command
Test that WGS TN case that fails in production can now be stored together with hermes fix in stage:  https://github.com/Clinical-Genomics/hermes/pull/133
Test that TGA TO case can STILL be stored together with hermes fix in stage:  https://github.com/Clinical-Genomics/hermes/pull/133
- **Web portal for Clinical …
=> fix: remove report generation

BALSAMIC/workflows/balsamic.smk, CHANGELOG.rst
See userstory: https://github.com/Clinical-Genomics/BALSAMIC/issues/1546
And discussion in Scout: https://github.com/Clinical-Genomics/scout/issues/5298#issuecomment-2705997660
NOTE: For this change to take affect we need to reformat the clinvar VCF
- renamed CLNACC to CLNVID for Clinvar annotations
Validation criteria to be added to …
=> feat: Add clinvarID to VCF

BALSAMIC/workflows/balsamic.smk, CHANGELOG.rst
Patch release `16.0.2`
As we are delaying the release of version 17.0.0 of balsamic we want to make a quick patch of the sleep time of a rule.
**No verification required as the patch is so tiny.** 
Procedure:
- Copy current cache in production to version 16.0.2
- Follow deployment instructions on atlas: https://atlas.scilifelab.se/infrastructure/bioinformatic_pipelines/BALSAMIC/balsamic_gitmodel/#steps-for-making-a-new-release
- increased sleep time to 25 minutes 
- **Stored files in …
=> feat: release v16.0.2

BALSAMIC/assets/scripts/collect_qc_metrics.py, CHANGELOG.rst
It was discovered during verification that the normal QC threshold for MEDIAN_COVERAGE was also applied to the tumor wgs. This is not a big deal as the tumor should always have much higher coverage than the normal, but it's still good to fix.
This fixes issue: https://github.com/Clinical-Genomics/BALSAMIC/issues/1549
- excluded MEDIAN_COVERAGE from tumor coverage qc threshold
- **Servers (configuration files …
=> fix: tumor qc threshold wgs

BALSAMIC/assets/scripts/sex_prediction_tga.py, CHANGELOG.rst
A bug was reported in cg-cancer in slack from prodbioinfo regarding a case in a small panel failing in the sex prediction step. A small investigation showed that this was due to a bug in the code where we're not properly handling panels without targets on the Y-chromosome.
In this fix I'm changing the filter of the coverage-file (antitarget or target) from requiring a total of 10 datapoints, to requiring at least 5 datapoints in Y and 5 datapoints in X. 
- fixed filter step in the sex-prediction script for TGA to skip sex prediction on files without at least 5 datapoints on Y and X
- …
=> fix: bug sex prediction

CHANGELOG.rst, docs/install.rst
Installing balsamic minor update v17.1.0 failed `pip install --no-cache-dir -U git+https://github.com/Clinical-Genomics/BALSAMIC` during installation of "datrie" because for some reason it upgraded Cython during its build-isolation to above version >3 and the gcc that we're using is the one on hasta and it's in the C89 version which was not compatible with Cython >3.  
Running: `python -m cython --version` in the old environment of balsamic v17.0.1 shows that we were using 0.29.34 and doing the same in the new environment after the fix shows that we're using the same version. 
This PR updates the installation instructions to add `"cython<3" to the conda installation and adding --no-build-isolation to the pip install which means that pip won't create a temporary virtual environment for …
=> chore: update install instructions
